App.prototype.start=function(){null!=this.bg&&null!=this.bg.parentNode&&this.bg.parentNode.removeChild(this.bg);this.restoreLibraries();this.spinner.stop();try{var b=this;window.onerror=function(m,t,y,C,z){"ResizeObserver loop limit exceeded"!=m&&(EditorUi.logError("Uncaught: "+(null!=m?m:""),t,y,C,z,null,!0),b.handleError({message:m},mxResources.get("unknownError"),null,null,null,null,!0))};if("1"!=urlParams.client&&"1"!=urlParams.embed){try{isLocalStorage&&window.addEventListener("storage",mxUtils.bind(this,
function(m){var t=this.getCurrentFile();EditorUi.debug("storage event",[m],[t]);null!=t&&".draft-alive-check"==m.key&&null!=m.newValue&&null!=t.draftId&&(this.draftAliveCheck=m.newValue,t.saveDraft())})),mxClient.IS_CHROMEAPP||EditorUi.isElectronApp||this.isOfflineApp()||null!=urlParams.open||!/www\.draw\.io$/.test(window.location.hostname)||this.editor.chromeless&&!this.editor.editable||this.showNameChangeBanner()}catch(m){}mxEvent.addListener(window,"hashchange",mxUtils.bind(this,function(m){try{this.hideDialog();
var t=this.getDiagramId(),y=this.getCurrentFile();null!=y&&y.getHash()==t||this.loadFile(t,!0)}catch(C){null!=document.body&&this.handleError(C,mxResources.get("errorLoadingFile"),mxUtils.bind(this,function(){var z=this.getCurrentFile();window.location.hash=null!=z?z.getHash():""}))}}))}if((null==window.location.hash||1>=window.location.hash.length)&&null!=urlParams.desc)try{this.loadDescriptor(JSON.parse(Graph.decompress(urlParams.desc)),null,mxUtils.bind(this,function(m){this.handleError(m,mxResources.get("errorLoadingFile"))}))}catch(m){this.handleError(m,
mxResources.get("errorLoadingFile"))}else if((null==window.location.hash||1>=window.location.hash.length)&&null!=urlParams.url)this.loadFile("U"+urlParams.url,!0);else if(null==this.getCurrentFile()){var e=mxUtils.bind(this,function(){if("1"==urlParams.client&&(null==window.location.hash||0==window.location.hash.length||"#P"==window.location.hash.substring(0,2))){var m=mxUtils.bind(this,function(C){Editor.isPngDataUrl(C)&&(C=Editor.extractGraphModelFromPng(C));var z=urlParams.title;z=null!=z?decodeURIComponent(z):
this.defaultFilename;C=new LocalFile(this,C,z,!0);null!=window.location.hash&&"#P"==window.location.hash.substring(0,2)&&(C.getHash=function(){return window.location.hash.substring(1)});this.fileLoaded(C);this.getCurrentFile().setModified(!this.editor.chromeless)}),t=window.opener||window.parent;if(t!=window){var y=urlParams.create;null!=y?m(t[decodeURIComponent(y)]):(y=urlParams.data,null!=y?m(decodeURIComponent(y)):this.installMessageHandler(mxUtils.bind(this,function(C,z){z.source==t&&m(C)})))}}else if(null==
this.dialog)if("1"==urlParams.demo)y=Editor.useLocalStorage,this.createFile(this.defaultFilename,null,null,null,null,null,null,!0),Editor.useLocalStorage=y;else{y=!1;try{y=null!=window.opener&&null!=window.opener.openFile}catch(C){}y?this.spinner.spin(document.body,mxResources.get("loading")):(y=this.getDiagramId(),!EditorUi.enableDrafts||null!=urlParams.mode||"draw.io"!=this.getServiceName()||null!=y&&0!=y.length||this.editor.isChromelessView()?null!=y&&0<y.length?this.loadFile(y,null,null,mxUtils.bind(this,
function(){var C=decodeURIComponent(urlParams.viewbox||"");if(""!=C)try{var z=JSON.parse(C);this.editor.graph.fitWindow(z,z.border)}catch(A){console.error(A)}})):"0"!=urlParams.splash||null!=urlParams.mode?this.loadFile():EditorUi.isElectronApp||this.createFile(this.defaultFilename,this.getFileData(),null,null,null,null,null,!0):this.checkDrafts())}}),f=decodeURIComponent(urlParams.create||"");if((null==window.location.hash||1>=window.location.hash.length)&&null!=f&&0<f.length&&this.spinner.spin(document.body,
mxResources.get("loading"))){var c=mxUtils.bind(this,function(){this.spinner.spin(document.body,mxResources.get("reconnecting"))&&(window.location.search=this.getSearch(["create","title"]))}),l=mxUtils.bind(this,function(m){this.spinner.stop();if("0"!=urlParams.splash){this.fileLoaded(new LocalFile(this,m,null));this.editor.graph.setEnabled(!1);this.mode=urlParams.mode;var t=urlParams.title;t=null!=t?decodeURIComponent(t):this.defaultFilename;m=this.getServiceCount(!0);isLocalStorage&&m++;var y=4>=
m?2:6<m?4:3;t=new CreateDialog(this,t,mxUtils.bind(this,function(C,z){if(null==z){this.hideDialog();var A=Editor.useLocalStorage;this.createFile(0<C.length?C:this.defaultFilename,this.getFileData(),null,null,null,!0,null,!0);Editor.useLocalStorage=A}else this.pickFolder(z,mxUtils.bind(this,function(J){this.createFile(C,this.getFileData(!0),null,z,null,!0,J)}))}),null,null,null,null,"1"==urlParams.browser,null,null,!0,y,null,null,null,this.editor.fileExtensions);this.showDialog(t.container,420,m>y?
390:280,!0,!1,mxUtils.bind(this,function(C){C&&null==this.getCurrentFile()&&this.showSplash()}));t.init()}});f=decodeURIComponent(f);if("http://"!=f.substring(0,7)&&"https://"!=f.substring(0,8))try{null!=window.opener&&null!=window.opener[f]?l(window.opener[f]):this.handleError(null,mxResources.get("errorLoadingFile"))}catch(m){this.handleError(m,mxResources.get("errorLoadingFile"))}else this.loadTemplate(f,function(m){l(m)},mxUtils.bind(this,function(m){this.handleError(m,mxResources.get("errorLoadingFile"),
c)}))}else(null==window.location.hash||1>=window.location.hash.length)&&null!=urlParams.state&&null!=this.stateArg&&"open"==this.stateArg.action?null!=this.stateArg.ids&&(window.history&&window.history.replaceState&&window.history.replaceState(null,null,window.location.pathname+this.getSearch(["state"])),window.location.hash="G"+this.stateArg.ids[0]):(null==window.location.hash||1>=window.location.hash.length)&&null!=this.drive&&null!=this.stateArg&&"create"==this.stateArg.action?(window.history&&
window.history.replaceState&&window.history.replaceState(null,null,window.location.pathname+this.getSearch(["state"])),this.setMode(App.MODE_GOOGLE),"0"==urlParams.splash?this.createFile(null!=urlParams.title?decodeURIComponent(urlParams.title):this.defaultFilename):this.actions.get("new").funct()):(null!=urlParams.open&&window.history&&window.history.replaceState&&(window.history.replaceState(null,null,window.location.pathname+this.getSearch(["open","sketch"])),window.location.hash=urlParams.open),
e())}}catch(m){this.handleError(m)}};App.prototype.loadDraft=function(b,e){this.createFile(this.defaultFilename,b,null,null,mxUtils.bind(this,function(){window.setTimeout(mxUtils.bind(this,function(){var f=this.getCurrentFile();null!=f&&(f.fileChanged(),null!=e&&e())}),0)}),null,null,!0)};