EditorUi.prototype.createShapePicker=function(b,e,k,l,B,q,D,N,S){var F=this.editor.graph,K=null;S=null!=S?S:function(f){f=f[0];var g=0,u=0;null!=f.geometry&&(g=f.geometry.width/2,u=f.geometry.height/2);return new mxPoint(F.snap(Math.round(b/F.view.scale)-F.view.translate.x-g),F.snap(Math.round(e/F.view.scale)-F.view.translate.y-u))};if(null!=D&&0<D.length){var R=this;F=this.editor.graph;K=document.createElement("div");B=F.view.getState(k);var d=null==k||null!=B&&F.isTransparentState(B)?null:F.copyStyle(k);
k=6>D.length?35*D.length:140;K.className="geToolbarContainer geSidebarContainer";K.style.cssText="position:absolute;left:"+b+"px;top:"+e+"px;width:"+k+"px;border-radius:10px;padding:4px;text-align:center;box-shadow:0px 0px 3px 1px #d1d1d1;padding: 6px 0 8px 0;z-index: "+mxPopupMenu.prototype.zIndex+1+";";N||mxUtils.setPrefixedStyle(K.style,"transform","translate(-22px,-22px)");null!=F.background&&F.background!=mxConstants.NONE&&(K.style.backgroundColor=F.background);F.container.appendChild(K);k=mxUtils.bind(this,
function(f){var g=document.createElement("a");g.className="geItem";g.style.cssText="position:relative;display:inline-block;position:relative;width:30px;height:30px;cursor:pointer;overflow:hidden;padding:1px";K.appendChild(g);null!=d&&"1"!=urlParams.sketch?this.sidebar.graph.pasteStyle(d,[f]):R.insertHandler([f],""!=f.value&&"1"!=urlParams.sketch,this.sidebar.graph.model);g.appendChild(this.sidebar.createVertexTemplateFromCells([f],f.geometry.width,f.geometry.height,"",!0,!1,null,!1,mxUtils.bind(this,
function(u){var x=F.cloneCell(f);if(null!=l)l(x);else{var A=S([x]);x.geometry.x=A.x;x.geometry.y=A.y;F.model.beginUpdate();try{F.addCell(x),F.model.isVertex(x)&&F.isAutoSizeCell(x)&&F.updateCellSize(x)}finally{F.model.endUpdate()}F.setSelectionCell(x);F.scrollCellToVisible(x);F.startEditingAtCell(x);null!=R.hoverIcons&&R.hoverIcons.update(F.view.getState(x))}null!=q&&q();mxEvent.consume(u)}),25,25))});for(B=0;B<(N?Math.min(D.length,4):D.length);B++)k(D[B]);D=K.offsetTop+K.clientHeight-(F.container.scrollTop+
F.container.offsetHeight);0<D&&(K.style.top=Math.max(F.container.scrollTop+22,e-D)+"px");D=K.offsetLeft+K.clientWidth-(F.container.scrollLeft+F.container.offsetWidth);0<D&&(K.style.left=Math.max(F.container.scrollLeft+22,b-D)+"px")}return K};
EditorUi.prototype.getCellsForShapePicker=function(b,e){e=mxUtils.bind(this,function(k,l,B,q){return this.editor.graph.createVertex(null,null,q||"",0,0,l||120,B||60,k,!1)});return[null!=b?this.editor.graph.cloneCell(b):e("text;html=1;align=center;verticalAlign=middle;resizable=0;points=[];autosize=1;strokeColor=none;fillColor=none;",40,20,"Text"),e("whiteSpace=wrap;html=1;"),e("ellipse;whiteSpace=wrap;html=1;"),e("rhombus;whiteSpace=wrap;html=1;",80,80),e("rounded=1;whiteSpace=wrap;html=1;"),e("shape=parallelogram;perimeter=parallelogramPerimeter;whiteSpace=wrap;html=1;fixedSize=1;"),
e("shape=trapezoid;perimeter=trapezoidPerimeter;whiteSpace=wrap;html=1;fixedSize=1;",120,60),e("shape=hexagon;perimeter=hexagonPerimeter2;whiteSpace=wrap;html=1;fixedSize=1;",120,80),e("shape=step;perimeter=stepPerimeter;whiteSpace=wrap;html=1;fixedSize=1;",120,80),e("shape=process;whiteSpace=wrap;html=1;backgroundOutline=1;"),e("triangle;whiteSpace=wrap;html=1;",60,80),e("shape=document;whiteSpace=wrap;html=1;boundedLbl=1;",120,80),e("shape=tape;whiteSpace=wrap;html=1;",120,100),e("ellipse;shape=cloud;whiteSpace=wrap;html=1;",
120,80),e("shape=singleArrow;whiteSpace=wrap;html=1;arrowWidth=0.4;arrowSize=0.4;",80,60),e("shape=waypoint;sketch=0;size=6;pointerEvents=1;points=[];fillColor=none;resizable=0;rotatable=0;perimeter=centerPerimeter;snapToPoint=1;",40,40)]};EditorUi.prototype.hideShapePicker=function(b){null!=this.shapePicker&&(this.shapePicker.parentNode.removeChild(this.shapePicker),this.shapePicker=null,b||null==this.shapePickerCallback||this.shapePickerCallback(),this.shapePickerCallback=null)};
EditorUi.prototype.onKeyDown=function(b){var e=this.editor.graph;if(9==b.which&&e.isEnabled()&&!mxEvent.isControlDown(b)){if(e.isEditing())if(mxEvent.isAltDown(b))e.stopEditing(!1);else try{var k=e.cellEditor.isContentEditing()&&e.cellEditor.isTextSelected();if(window.getSelection&&e.cellEditor.isContentEditing()&&!k&&!mxClient.IS_IE&&!mxClient.IS_IE11){var l=window.getSelection(),B=0<l.rangeCount?l.getRangeAt(0).commonAncestorContainer:null;k=null!=B&&("LI"==B.nodeName||null!=B.parentNode&&"LI"==
B.parentNode.nodeName)}k?document.execCommand(mxEvent.isShiftDown(b)?"outdent":"indent",!1,null):mxEvent.isShiftDown(b)?e.stopEditing(!1):e.cellEditor.insertTab(e.cellEditor.isContentEditing()?null:4)}catch(q){}else mxEvent.isAltDown(b)?e.selectParentCell():e.selectCell(!mxEvent.isShiftDown(b));mxEvent.consume(b)}};
EditorUi.prototype.onKeyPress=function(b){var e=this.editor.graph;!this.isImmediateEditingEvent(b)||e.isEditing()||e.isSelectionEmpty()||0===b.which||27===b.which||mxEvent.isAltDown(b)||mxEvent.isControlDown(b)||mxEvent.isMetaDown(b)||(e.escape(),e.startEditing(),mxClient.IS_FF&&(e=e.cellEditor,null!=e.textarea&&(e.textarea.innerHTML=String.fromCharCode(b.which),b=document.createRange(),b.selectNodeContents(e.textarea),b.collapse(!1),e=window.getSelection(),e.removeAllRanges(),e.addRange(b))))};
EditorUi.prototype.isImmediateEditingEvent=function(b){return!0};
EditorUi.prototype.updateCssForMarker=function(b,e,k,l,B){b.style.verticalAlign="top";b.style.height="21px";b.style.width="21px";b.innerText="";"flexArrow"==k?b.className=null!=l&&l!=mxConstants.NONE?"geSprite geSprite-"+e+"blocktrans":"geSprite geSprite-noarrow":(k=this.getImageForMarker(l,B),null!=k?(l=document.createElement("img"),l.className="geAdaptiveAsset",l.style.position="absolute",l.style.marginTop="0.5px",l.setAttribute("src",k),b.className="","end"==e&&mxUtils.setPrefixedStyle(l.style,
"transform","scaleX(-1)"),b.appendChild(l)):(b.className="geSprite geSprite-noarrow",b.innerHTML=mxUtils.htmlEntities(mxResources.get("none")),b.style.backgroundImage="none",b.style.verticalAlign="top",b.style.marginTop="4px",b.style.fontSize="10px",b.style.filter="none",b.style.color=this.defaultStrokeColor,b.nextSibling.style.marginTop="0px"))};
EditorUi.prototype.getImageForMarker=function(b,e){var k=null;b==mxConstants.ARROW_CLASSIC?k="1"!=e?Format.classicMarkerImage.src:Format.classicFilledMarkerImage.src:b==mxConstants.ARROW_CLASSIC_THIN?k="1"!=e?Format.classicThinMarkerImage.src:Format.openThinFilledMarkerImage.src:b==mxConstants.ARROW_OPEN?k=Format.openFilledMarkerImage.src:b==mxConstants.ARROW_OPEN_THIN?k=Format.openThinFilledMarkerImage.src:b==mxConstants.ARROW_BLOCK?k="1"!=e?Format.blockMarkerImage.src:Format.blockFilledMarkerImage.src:
b==mxConstants.ARROW_BLOCK_THIN?k="1"!=e?Format.blockThinMarkerImage.src:Format.blockThinFilledMarkerImage.src:b==mxConstants.ARROW_OVAL?k="1"!=e?Format.ovalMarkerImage.src:Format.ovalFilledMarkerImage.src:b==mxConstants.ARROW_DIAMOND?k="1"!=e?Format.diamondMarkerImage.src:Format.diamondFilledMarkerImage.src:b==mxConstants.ARROW_DIAMOND_THIN?k="1"!=e?Format.diamondThinMarkerImage.src:Format.diamondThinFilledMarkerImage.src:"doubleBlock"==b?k="1"!=e?Format.doubleBlockMarkerImage.src:Format.doubleBlockFilledMarkerImage.src:
"box"==b?k=Format.boxMarkerImage.src:"halfCircle"==b?k=Format.halfCircleMarkerImage.src:"openAsync"==b?k=Format.openAsyncFilledMarkerImage.src:"async"==b?k="1"!=e?Format.asyncMarkerImage.src:Format.asyncFilledMarkerImage.src:"dash"==b?k=Format.dashMarkerImage.src:"baseDash"==b?k=Format.baseDashMarkerImage.src:"cross"==b?k=Format.crossMarkerImage.src:"circle"==b?k=Format.circleMarkerImage.src:"circlePlus"==b?k=Format.circlePlusMarkerImage.src:"ERone"==b?k=Format.EROneMarkerImage.src:"ERmandOne"==b?
k=Format.ERmandOneMarkerImage.src:"ERmany"==b?k=Format.ERmanyMarkerImage.src:"ERoneToMany"==b?k=Format.ERoneToManyMarkerImage.src:"ERzeroToOne"==b?k=Format.ERzeroToOneMarkerImage.src:"ERzeroToMany"==b&&(k=Format.ERzeroToManyMarkerImage.src);return k};EditorUi.prototype.createMenus=function(){return null};
EditorUi.prototype.updatePasteActionStates=function(){var b=this.editor.graph,e=this.actions.get("paste"),k=this.actions.get("pasteHere");e.setEnabled(this.editor.graph.cellEditor.isContentEditing()||(!mxClient.IS_FF&&null!=navigator.clipboard||!mxClipboard.isEmpty())&&b.isEnabled()&&!b.isCellLocked(b.getDefaultParent()));k.setEnabled(e.isEnabled())};
EditorUi.prototype.initClipboard=function(){var b=this,e=mxClipboard.cut;mxClipboard.cut=function(q){q.cellEditor.isContentEditing()?document.execCommand("cut",!1,null):e.apply(this,arguments);b.updatePasteActionStates()};mxClipboard.copy=function(q){var D=null;if(q.cellEditor.isContentEditing())document.execCommand("copy",!1,null);else{D=D||q.getSelectionCells();D=q.getExportableCells(q.model.getTopmostCells(D));for(var N={},S=q.createCellLookup(D),F=q.cloneCells(D,null,N),K=new mxGraphModel,R=K.getChildAt(K.getRoot(),
0),d=0;d<F.length;d++){K.add(R,F[d]);var f=q.view.getState(D[d]);if(null!=f){var g=q.getCellGeometry(F[d]);null!=g&&g.relative&&!K.isEdge(D[d])&&null==S[mxObjectIdentity.get(K.getParent(D[d]))]&&(g.offset=null,g.relative=!1,g.x=f.x/f.view.scale-f.view.translate.x,g.y=f.y/f.view.scale-f.view.translate.y)}}q.updateCustomLinks(q.createCellMapping(N,S),F);mxClipboard.insertCount=1;mxClipboard.setCells(F)}b.updatePasteActionStates();return D};var k=mxClipboard.paste;mxClipboard.paste=function(q){var D=
null;q.cellEditor.isContentEditing()?document.execCommand("paste",!1,null):D=k.apply(this,arguments);b.updatePasteActionStates();return D};var l=this.editor.graph.cellEditor.startEditing;this.editor.graph.cellEditor.startEditing=function(){l.apply(this,arguments);b.updatePasteActionStates()};var B=this.editor.graph.cellEditor.stopEditing;this.editor.graph.cellEditor.stopEditing=function(q,D){B.apply(this,arguments);b.updatePasteActionStates()};this.updatePasteActionStates()};
EditorUi.prototype.lazyZoomDelay=20;EditorUi.prototype.wheelZoomDelay=400;EditorUi.prototype.buttonZoomDelay=600;
EditorUi.prototype.initCanvas=function(){var b=this.editor.graph;b.timerAutoScroll=!0;b.getPagePadding=function(){return new mxPoint(Math.max(0,Math.round((b.container.offsetWidth-34)/b.view.scale)),Math.max(0,Math.round((b.container.offsetHeight-34)/b.view.scale)))};b.view.getBackgroundPageBounds=function(){var Y=this.graph.getPageLayout(),p=this.graph.getPageSize();return new mxRectangle(this.scale*(this.translate.x+Y.x*p.width),this.scale*(this.translate.y+Y.y*p.height),this.scale*Y.width*p.width,
this.scale*Y.height*p.height)};b.getPreferredPageSize=function(Y,p,E){Y=this.getPageLayout();p=this.getPageSize();return new mxRectangle(0,0,Y.width*p.width,Y.height*p.height)};var e=null,k=this;if(this.editor.isChromelessView()){this.chromelessResize=e=mxUtils.bind(this,function(Y,p,E,Q){if(null!=b.container&&!b.isViewer()){E=null!=E?E:0;Q=null!=Q?Q:0;var Z=b.pageVisible?b.view.getBackgroundPageBounds():b.getGraphBounds(),W=mxUtils.hasScrollbars(b.container),X=b.view.translate,da=b.view.scale,la=
mxRectangle.fromRectangle(Z);la.x=la.x/da-X.x;la.y=la.y/da-X.y;la.width/=da;la.height/=da;X=b.container.scrollTop;var pa=b.container.scrollLeft,ma=8<=document.documentMode?20:14;if(8==document.documentMode||9==document.documentMode)ma+=3;var qa=b.container.offsetWidth-ma;ma=b.container.offsetHeight-ma;Y=Y?Math.max(.3,Math.min(p||1,qa/la.width)):da;p=(qa-Y*la.width)/2/Y;var za=0==this.lightboxVerticalDivider?0:(ma-Y*la.height)/this.lightboxVerticalDivider/Y;W&&(p=Math.max(p,0),za=Math.max(za,0));if(W||
Z.width<qa||Z.height<ma)b.view.scaleAndTranslate(Y,Math.floor(p-la.x),Math.floor(za-la.y)),b.container.scrollTop=X*Y/da,b.container.scrollLeft=pa*Y/da;else if(0!=E||0!=Q)Z=b.view.translate,b.view.setTranslate(Math.floor(Z.x+E/da),Math.floor(Z.y+Q/da))}});this.chromelessWindowResize=mxUtils.bind(this,function(){this.chromelessResize(!1)});var l=mxUtils.bind(this,function(){this.chromelessWindowResize(!1)});mxEvent.addListener(window,"resize",l);this.destroyFunctions.push(function(){mxEvent.removeListener(window,
"resize",l)});this.editor.addListener("resetGraphView",mxUtils.bind(this,function(){this.chromelessResize(!0)}));this.actions.get("zoomIn").funct=mxUtils.bind(this,function(Y){b.zoomIn();this.chromelessResize(!1)});this.actions.get("zoomOut").funct=mxUtils.bind(this,function(Y){b.zoomOut();this.chromelessResize(!1)});if("0"!=urlParams.toolbar){var B=JSON.parse(decodeURIComponent(urlParams["toolbar-config"]||"{}"));this.chromelessToolbar=document.createElement("div");this.chromelessToolbar.style.position=
"fixed";this.chromelessToolbar.style.overflow="hidden";this.chromelessToolbar.style.boxSizing="border-box";this.chromelessToolbar.style.whiteSpace="nowrap";this.chromelessToolbar.style.padding="10px 10px 8px 10px";this.chromelessToolbar.style.left=b.isViewer()?"0":"50%";mxClient.IS_IE||mxClient.IS_IE11?(this.chromelessToolbar.style.backgroundColor="#ffffff",this.chromelessToolbar.style.border="3px solid black"):this.chromelessToolbar.style.backgroundColor="#000000";mxUtils.setPrefixedStyle(this.chromelessToolbar.style,
"borderRadius","16px");mxUtils.setPrefixedStyle(this.chromelessToolbar.style,"transition","opacity 600ms ease-in-out");var q=mxUtils.bind(this,function(){var Y=mxUtils.getCurrentStyle(b.container);b.isViewer()?this.chromelessToolbar.style.top="0":this.chromelessToolbar.style.bottom=(null!=Y?parseInt(Y["margin-bottom"]||0):0)+(null!=this.tabContainer?20+parseInt(this.tabContainer.style.height):20)+"px"});this.editor.addListener("resetGraphView",q);q();var D=0;q=mxUtils.bind(this,function(Y,p,E){D++;
var Q=document.createElement("span");Q.style.paddingLeft="8px";Q.style.paddingRight="8px";Q.style.cursor="pointer";mxEvent.addListener(Q,"click",Y);null!=E&&Q.setAttribute("title",E);Y=document.createElement("img");Y.setAttribute("border","0");Y.setAttribute("src",p);Y.style.width="36px";Y.style.filter="invert(100%)";Q.appendChild(Y);this.chromelessToolbar.appendChild(Q);return Q});if(null!=B.backBtn){var N=Graph.sanitizeLink(B.backBtn.url);null!=N&&q(mxUtils.bind(this,function(Y){window.location.href=
N;mxEvent.consume(Y)}),Editor.backImage,mxResources.get("back",null,"Back"))}if(this.isPagesEnabled()){var S=q(mxUtils.bind(this,function(Y){this.actions.get("previousPage").funct();mxEvent.consume(Y)}),Editor.previousImage,mxResources.get("previousPage")),F=document.createElement("div");F.style.fontFamily=Editor.defaultHtmlFont;F.style.display="inline-block";F.style.verticalAlign="top";F.style.fontWeight="bold";F.style.marginTop="8px";F.style.fontSize="14px";F.style.color=mxClient.IS_IE||mxClient.IS_IE11?
"#000000":"#ffffff";this.chromelessToolbar.appendChild(F);var K=q(mxUtils.bind(this,function(Y){this.actions.get("nextPage").funct();mxEvent.consume(Y)}),Editor.nextImage,mxResources.get("nextPage")),R=mxUtils.bind(this,function(){null!=this.pages&&1<this.pages.length&&null!=this.currentPage&&(F.innerText="",mxUtils.write(F,mxUtils.indexOf(this.pages,this.currentPage)+1+" / "+this.pages.length))});S.style.paddingLeft="0px";S.style.paddingRight="4px";K.style.paddingLeft="4px";K.style.paddingRight=
"0px";var d=mxUtils.bind(this,function(){null!=this.pages&&1<this.pages.length&&null!=this.currentPage?(K.style.display="",S.style.display="",F.style.display="inline-block"):(K.style.display="none",S.style.display="none",F.style.display="none");R()});this.editor.addListener("resetGraphView",d);this.editor.addListener("pageSelected",R)}q(mxUtils.bind(this,function(Y){this.actions.get("zoomOut").funct();mxEvent.consume(Y)}),Editor.zoomOutImage,mxResources.get("zoomOut")+" (Alt+Mousewheel)");q(mxUtils.bind(this,
function(Y){this.actions.get("zoomIn").funct();mxEvent.consume(Y)}),Editor.zoomInImage,mxResources.get("zoomIn")+" (Alt+Mousewheel)");q(mxUtils.bind(this,function(Y){b.isLightboxView()?(1==b.view.scale?this.lightboxFit():b.zoomTo(1),this.chromelessResize(!1)):this.chromelessResize(!0);mxEvent.consume(Y)}),Editor.zoomFitImage,mxResources.get("fit"));var f=null,g=null,u=mxUtils.bind(this,function(Y){null!=f&&(window.clearTimeout(f),f=null);null!=g&&(window.clearTimeout(g),g=null);f=window.setTimeout(mxUtils.bind(this,
function(){mxUtils.setOpacity(this.chromelessToolbar,0);f=null;g=window.setTimeout(mxUtils.bind(this,function(){this.chromelessToolbar.style.display="none";g=null}),600)}),Y||200)}),x=mxUtils.bind(this,function(Y){null!=f&&(window.clearTimeout(f),f=null);null!=g&&(window.clearTimeout(g),g=null);this.chromelessToolbar.style.display="";mxUtils.setOpacity(this.chromelessToolbar,Y||30)});if("1"==urlParams.layers){this.layersDialog=null;var A=q(mxUtils.bind(this,function(Y){if(null!=this.layersDialog)this.layersDialog.parentNode.removeChild(this.layersDialog),
this.layersDialog=null;else{this.layersDialog=b.createLayersDialog(null,!0);mxEvent.addListener(this.layersDialog,"mouseleave",mxUtils.bind(this,function(){this.layersDialog.parentNode.removeChild(this.layersDialog);this.layersDialog=null}));var p=A.getBoundingClientRect();mxUtils.setPrefixedStyle(this.layersDialog.style,"borderRadius","5px");this.layersDialog.style.position="fixed";this.layersDialog.style.fontFamily=Editor.defaultHtmlFont;this.layersDialog.style.width="160px";this.layersDialog.style.padding=
"4px 2px 4px 2px";this.layersDialog.style.left=p.left+"px";this.layersDialog.style.bottom=parseInt(this.chromelessToolbar.style.bottom)+this.chromelessToolbar.offsetHeight+4+"px";mxClient.IS_IE||mxClient.IS_IE11?(this.layersDialog.style.backgroundColor="#ffffff",this.layersDialog.style.border="2px solid black",this.layersDialog.style.color="#000000"):(this.layersDialog.style.backgroundColor="#000000",this.layersDialog.style.color="#ffffff",mxUtils.setOpacity(this.layersDialog,80));p=mxUtils.getCurrentStyle(this.editor.graph.container);
this.layersDialog.style.zIndex=p.zIndex;document.body.appendChild(this.layersDialog);this.editor.fireEvent(new mxEventObject("layersDialogShown"))}mxEvent.consume(Y)}),Editor.layersImage,mxResources.get("layers")),H=b.getModel();H.addListener(mxEvent.CHANGE,function(){A.style.display=1<H.getChildCount(H.root)?"":"none"})}("1"!=urlParams.openInSameWin||navigator.standalone)&&this.addChromelessToolbarItems(q);null==this.editor.editButtonLink&&null==this.editor.editButtonFunc||q(mxUtils.bind(this,function(Y){null!=
this.editor.editButtonFunc?this.editor.editButtonFunc():"_blank"==this.editor.editButtonLink?this.editor.editAsNew(this.getEditBlankXml()):b.openLink(this.editor.editButtonLink,"editWindow");mxEvent.consume(Y)}),Editor.editImage,mxResources.get("edit"));if(null!=this.lightboxToolbarActions)for(d=0;d<this.lightboxToolbarActions.length;d++){var P=this.lightboxToolbarActions[d];P.elem=q(P.fn,P.icon,P.tooltip)}if(null!=B.refreshBtn){var M=null==B.refreshBtn.url?null:Graph.sanitizeLink(B.refreshBtn.url);
q(mxUtils.bind(this,function(Y){null!=M?window.location.href=M:window.location.reload();mxEvent.consume(Y)}),Editor.refreshImage,mxResources.get("refresh",null,"Refresh"))}null!=B.fullscreenBtn&&window.self!==window.top&&q(mxUtils.bind(this,function(Y){B.fullscreenBtn.url?b.openLink(B.fullscreenBtn.url):b.openLink(window.location.href);mxEvent.consume(Y)}),Editor.fullscreenImage,mxResources.get("openInNewWindow",null,"Open in New Window"));(B.closeBtn&&window.self===window.top||b.lightbox&&("1"==
urlParams.close||this.container!=document.body))&&q(mxUtils.bind(this,function(Y){"1"==urlParams.close||B.closeBtn?window.close():(this.destroy(),mxEvent.consume(Y))}),Editor.closeImage,mxResources.get("close")+" (Escape)");this.chromelessToolbar.style.display="none";b.isViewer()||mxUtils.setPrefixedStyle(this.chromelessToolbar.style,"transform","translate(-50%,0)");b.container.appendChild(this.chromelessToolbar);mxEvent.addListener(b.container,mxClient.IS_POINTER?"pointermove":"mousemove",mxUtils.bind(this,
function(Y){mxEvent.isTouchEvent(Y)||(mxEvent.isShiftDown(Y)||x(30),u())}));mxEvent.addListener(this.chromelessToolbar,mxClient.IS_POINTER?"pointermove":"mousemove",function(Y){mxEvent.consume(Y)});mxEvent.addListener(this.chromelessToolbar,"mouseenter",mxUtils.bind(this,function(Y){b.tooltipHandler.resetTimer();b.tooltipHandler.hideTooltip();mxEvent.isShiftDown(Y)?u():x(100)}));mxEvent.addListener(this.chromelessToolbar,"mousemove",mxUtils.bind(this,function(Y){mxEvent.isShiftDown(Y)?u():x(100);
mxEvent.consume(Y)}));mxEvent.addListener(this.chromelessToolbar,"mouseleave",mxUtils.bind(this,function(Y){mxEvent.isTouchEvent(Y)||x(30)}));var G=b.getTolerance();b.addMouseListener({startX:0,startY:0,scrollLeft:0,scrollTop:0,mouseDown:function(Y,p){this.startX=p.getGraphX();this.startY=p.getGraphY();this.scrollLeft=b.container.scrollLeft;this.scrollTop=b.container.scrollTop},mouseMove:function(Y,p){},mouseUp:function(Y,p){mxEvent.isTouchEvent(p.getEvent())&&Math.abs(this.scrollLeft-b.container.scrollLeft)<
G&&Math.abs(this.scrollTop-b.container.scrollTop)<G&&Math.abs(this.startX-p.getGraphX())<G&&Math.abs(this.startY-p.getGraphY())<G&&(0<parseFloat(k.chromelessToolbar.style.opacity||0)?u():x(30))}})}this.editor.editable||this.addChromelessClickHandler()}else if(this.editor.extendCanvas){var ia=b.view.validate;b.view.validate=function(){if(null!=this.graph.container&&mxUtils.hasScrollbars(this.graph.container)){var Y=this.graph.getPagePadding(),p=this.graph.getPageSize();this.translate.x=Y.x-(this.x0||
0)*p.width;this.translate.y=Y.y-(this.y0||0)*p.height}ia.apply(this,arguments)};if(!b.isViewer()){var ja=b.sizeDidChange;b.sizeDidChange=function(){if(null!=this.container&&mxUtils.hasScrollbars(this.container)){var Y=this.getPageLayout(),p=this.getPagePadding(),E=this.getPageSize(),Q=Math.ceil(2*p.x+Y.width*E.width),Z=Math.ceil(2*p.y+Y.height*E.height),W=b.minimumGraphSize;if(null==W||W.width!=Q||W.height!=Z)b.minimumGraphSize=new mxRectangle(0,0,Q,Z);Q=p.x-Y.x*E.width;p=p.y-Y.y*E.height;this.autoTranslate||
this.view.translate.x==Q&&this.view.translate.y==p?ja.apply(this,arguments):(this.autoTranslate=!0,this.view.x0=Y.x,this.view.y0=Y.y,Y=b.view.translate.x,E=b.view.translate.y,b.view.setTranslate(Q,p),b.container.scrollLeft+=Math.round((Q-Y)*b.view.scale),b.container.scrollTop+=Math.round((p-E)*b.view.scale),this.autoTranslate=!1)}else this.fireEvent(new mxEventObject(mxEvent.SIZE,"bounds",this.getGraphBounds()))}}}var ha=b.view.getBackgroundPane(),ba=b.view.getDrawPane();b.cumulativeZoomFactor=1;
var oa=null,sa=null,J=null,V=null,T=null,ca=function(Y){null!=oa&&window.clearTimeout(oa);0<=Y&&window.setTimeout(function(){if(!b.isMouseDown||V)oa=window.setTimeout(mxUtils.bind(this,function(){b.isFastZoomEnabled()&&(null!=b.view.backgroundPageShape&&null!=b.view.backgroundPageShape.node&&(mxUtils.setPrefixedStyle(b.view.backgroundPageShape.node.style,"transform-origin",null),mxUtils.setPrefixedStyle(b.view.backgroundPageShape.node.style,"transform",null)),ba.style.transformOrigin="",ha.style.transformOrigin=
"",mxClient.IS_SF?(ba.style.transform="scale(1)",ha.style.transform="scale(1)",window.setTimeout(function(){ba.style.transform="";ha.style.transform=""},0)):(ba.style.transform="",ha.style.transform=""),b.view.getDecoratorPane().style.opacity="",b.view.getOverlayPane().style.opacity="");var p=new mxPoint(b.container.scrollLeft,b.container.scrollTop),E=mxUtils.getOffset(b.container),Q=b.view.scale,Z=0,W=0;null!=sa&&(Z=b.container.offsetWidth/2-sa.x+E.x,W=b.container.offsetHeight/2-sa.y+E.y);b.zoom(b.cumulativeZoomFactor,
null,b.isFastZoomEnabled()?20:null);b.view.scale!=Q&&(null!=J&&(Z+=p.x-J.x,W+=p.y-J.y),null!=e&&k.chromelessResize(!1,null,Z*(b.cumulativeZoomFactor-1),W*(b.cumulativeZoomFactor-1)),!mxUtils.hasScrollbars(b.container)||0==Z&&0==W||(b.container.scrollLeft-=Z*(b.cumulativeZoomFactor-1),b.container.scrollTop-=W*(b.cumulativeZoomFactor-1)));null!=T&&ba.setAttribute("filter",T);b.cumulativeZoomFactor=1;T=V=sa=J=oa=null}),null!=Y?Y:b.isFastZoomEnabled()?k.wheelZoomDelay:k.lazyZoomDelay)},0)};b.lazyZoom=
function(Y,p,E,Q){Q=null!=Q?Q:this.zoomFactor;(p=p||!b.scrollbars)&&(sa=new mxPoint(b.container.offsetLeft+b.container.clientWidth/2,b.container.offsetTop+b.container.clientHeight/2));Y?.15>=this.view.scale*this.cumulativeZoomFactor?this.cumulativeZoomFactor*=(this.view.scale+.05)/this.view.scale:(this.cumulativeZoomFactor*=Q,this.cumulativeZoomFactor=Math.round(this.view.scale*this.cumulativeZoomFactor*100)/100/this.view.scale):.15>=this.view.scale*this.cumulativeZoomFactor?this.cumulativeZoomFactor*=
(this.view.scale-.05)/this.view.scale:(this.cumulativeZoomFactor/=Q,this.cumulativeZoomFactor=Math.round(this.view.scale*this.cumulativeZoomFactor*100)/100/this.view.scale);this.cumulativeZoomFactor=Math.max(.05,Math.min(this.view.scale*this.cumulativeZoomFactor,160))/this.view.scale;b.isFastZoomEnabled()&&(null==T&&""!=ba.getAttribute("filter")&&(T=ba.getAttribute("filter"),ba.removeAttribute("filter")),J=new mxPoint(b.container.scrollLeft,b.container.scrollTop),Y=p||null==sa?b.container.scrollLeft+
b.container.clientWidth/2:sa.x+b.container.scrollLeft-b.container.offsetLeft,Q=p||null==sa?b.container.scrollTop+b.container.clientHeight/2:sa.y+b.container.scrollTop-b.container.offsetTop,ba.style.transformOrigin=Y+"px "+Q+"px",ba.style.transform="scale("+this.cumulativeZoomFactor+")",ha.style.transformOrigin=Y+"px "+Q+"px",ha.style.transform="scale("+this.cumulativeZoomFactor+")",null!=b.view.backgroundPageShape&&null!=b.view.backgroundPageShape.node&&(Y=b.view.backgroundPageShape.node,mxUtils.setPrefixedStyle(Y.style,
"transform-origin",(p||null==sa?b.container.clientWidth/2+b.container.scrollLeft-Y.offsetLeft+"px":sa.x+b.container.scrollLeft-Y.offsetLeft-b.container.offsetLeft+"px")+" "+(p||null==sa?b.container.clientHeight/2+b.container.scrollTop-Y.offsetTop+"px":sa.y+b.container.scrollTop-Y.offsetTop-b.container.offsetTop+"px")),mxUtils.setPrefixedStyle(Y.style,"transform","scale("+this.cumulativeZoomFactor+")")),b.view.getDecoratorPane().style.opacity="0",b.view.getOverlayPane().style.opacity="0",null!=k.hoverIcons&&
k.hoverIcons.reset());ca(b.isFastZoomEnabled()?E:0)};mxEvent.addGestureListeners(b.container,function(Y){null!=oa&&window.clearTimeout(oa)},null,function(Y){1!=b.cumulativeZoomFactor&&ca(0)});mxEvent.addListener(b.container,"scroll",function(Y){null==oa||b.isMouseDown||1==b.cumulativeZoomFactor||ca(0)});mxEvent.addMouseWheelListener(mxUtils.bind(this,function(Y,p,E,Q,Z){b.fireEvent(new mxEventObject("wheel"));if(null==this.dialogs||0==this.dialogs.length)if(!b.scrollbars&&!E&&b.isScrollWheelEvent(Y))E=
b.view.getTranslate(),Q=40/b.view.scale,mxEvent.isShiftDown(Y)?b.view.setTranslate(E.x+(p?-Q:Q),E.y):b.view.setTranslate(E.x,E.y+(p?Q:-Q));else if(E||b.isZoomWheelEvent(Y))for(var W=mxEvent.getSource(Y);null!=W;){if(W==b.container)return b.tooltipHandler.hideTooltip(),sa=null!=Q&&null!=Z?new mxPoint(Q,Z):new mxPoint(mxEvent.getClientX(Y),mxEvent.getClientY(Y)),V=E,E=b.zoomFactor,Q=null,Y.ctrlKey&&null!=Y.deltaY&&40>Math.abs(Y.deltaY)&&Math.round(Y.deltaY)!=Y.deltaY?E=1+Math.abs(Y.deltaY)/20*(E-1):
null!=Y.movementY&&"pointermove"==Y.type&&(E=1+Math.max(1,Math.abs(Y.movementY))/20*(E-1),Q=-1),b.lazyZoom(p,null,Q,E),mxEvent.consume(Y),!1;W=W.parentNode}}),b.container);b.panningHandler.zoomGraph=function(Y){b.cumulativeZoomFactor=Y.scale;b.lazyZoom(0<Y.scale,!0);mxEvent.consume(Y)}};EditorUi.prototype.addChromelessToolbarItems=function(b){b(mxUtils.bind(this,function(e){this.actions.get("print").funct();mxEvent.consume(e)}),Editor.printImage,mxResources.get("print"))};
EditorUi.prototype.isPagesEnabled=function(){return this.editor.editable||"1"!=urlParams["hide-pages"]};EditorUi.prototype.createTemporaryGraph=function(b){return Graph.createOffscreenGraph(b)};EditorUi.prototype.addChromelessClickHandler=function(){var b=urlParams.highlight;null!=b&&0<b.length&&(b="#"+b);this.editor.graph.addClickHandler(b)};
EditorUi.prototype.toggleFormatPanel=function(b){b=null!=b?b:0==this.formatWidth;null!=this.format&&(this.formatWidth=b?240:0,this.formatContainer.style.display=b?"":"none",this.refresh(),this.format.refresh(),this.fireEvent(new mxEventObject("formatWidthChanged")))};EditorUi.prototype.isFormatPanelVisible=function(){return 0<this.formatWidth};
EditorUi.prototype.lightboxFit=function(b){if(this.isDiagramEmpty())this.editor.graph.view.setScale(1);else{var e=urlParams.border,k=60;null!=e&&(k=parseInt(e));this.editor.graph.maxFitScale=this.lightboxMaxFitScale;this.editor.graph.fit(k,null,null,null,null,null,b);this.editor.graph.maxFitScale=null}};EditorUi.prototype.isDiagramEmpty=function(){var b=this.editor.graph.getModel();return 1==b.getChildCount(b.root)&&0==b.getChildCount(b.getChildAt(b.root,0))};
EditorUi.prototype.isSelectionAllowed=function(b){return"SELECT"==mxEvent.getSource(b).nodeName||"INPUT"==mxEvent.getSource(b).nodeName&&mxUtils.isAncestorNode(this.formatContainer,mxEvent.getSource(b))};EditorUi.prototype.addBeforeUnloadListener=function(){window.onbeforeunload=mxUtils.bind(this,function(){if(!this.editor.isChromelessView())return this.onBeforeUnload()})};EditorUi.prototype.onBeforeUnload=function(){if(this.editor.modified)return mxResources.get("allChangesLost")};
EditorUi.prototype.open=function(){try{null!=window.opener&&null!=window.opener.openFile&&window.opener.openFile.setConsumer(mxUtils.bind(this,function(b,e){try{var k=mxUtils.parseXml(b);this.editor.setGraphXml(k.documentElement);this.editor.setModified(!1);this.editor.undoManager.clear();null!=e&&(this.editor.setFilename(e),this.updateDocumentTitle())}catch(l){mxUtils.alert(mxResources.get("invalidOrMissingFile")+": "+l.message)}}))}catch(b){}this.editor.graph.view.validate();this.editor.graph.sizeDidChange();
this.editor.fireEvent(new mxEventObject("resetGraphView"))};EditorUi.prototype.showPopupMenu=function(b,e,k,l){this.editor.graph.popupMenuHandler.hideMenu();var B=new mxPopupMenu(b);B.div.className+=" geMenubarMenu";B.smartSeparators=!0;B.showDisabled=!0;B.autoExpand=!0;B.hideMenu=mxUtils.bind(this,function(){mxPopupMenu.prototype.hideMenu.apply(B,arguments);B.destroy()});B.popup(e,k,null,l);this.setCurrentMenu(B)};
EditorUi.prototype.setCurrentMenu=function(b,e){this.currentMenuElt=e;this.currentMenu=b;this.hideShapePicker()};EditorUi.prototype.resetCurrentMenu=function(){this.currentMenu=this.currentMenuElt=null};EditorUi.prototype.hideCurrentMenu=function(){null!=this.currentMenu&&(this.currentMenu.hideMenu(),this.resetCurrentMenu())};EditorUi.prototype.updateDocumentTitle=function(){var b=this.editor.getOrCreateFilename();null!=this.editor.appName&&(b+=" - "+this.editor.appName);document.title=b};
EditorUi.prototype.createHoverIcons=function(){return new HoverIcons(this.editor.graph)};EditorUi.prototype.redo=function(){try{this.editor.graph.isEditing()?document.execCommand("redo",!1,null):this.editor.undoManager.redo()}catch(b){}};EditorUi.prototype.undo=function(){try{var b=this.editor.graph;if(b.isEditing()){var e=b.cellEditor.textarea.innerHTML;document.execCommand("undo",!1,null);e==b.cellEditor.textarea.innerHTML&&(b.stopEditing(!0),this.editor.undoManager.undo())}else this.editor.undoManager.undo()}catch(k){}};
EditorUi.prototype.canRedo=function(){return this.editor.graph.isEditing()||this.editor.undoManager.canRedo()};EditorUi.prototype.canUndo=function(){return this.editor.graph.isEditing()||this.editor.undoManager.canUndo()};EditorUi.prototype.getEditBlankXml=function(){return mxUtils.getXml(this.editor.getGraphXml())};EditorUi.prototype.getUrl=function(b){b=null!=b?b:window.location.pathname;var e=0<b.indexOf("?")?1:0,k;for(k in urlParams)b=0==e?b+"?":b+"&",b+=k+"="+urlParams[k],e++;return b};
EditorUi.prototype.setScrollbars=function(b){var e=this.editor.graph,k=e.container.style.overflow;e.scrollbars=b;this.editor.updateGraphComponents();k!=e.container.style.overflow&&(e.container.scrollTop=0,e.container.scrollLeft=0,e.view.scaleAndTranslate(1,0,0),this.resetScrollbars());this.fireEvent(new mxEventObject("scrollbarsChanged"))};EditorUi.prototype.hasScrollbars=function(){return this.editor.graph.scrollbars};
EditorUi.prototype.resetScrollbars=function(){var b=this.editor.graph;if(!this.editor.extendCanvas)b.container.scrollTop=0,b.container.scrollLeft=0,mxUtils.hasScrollbars(b.container)||b.view.setTranslate(0,0);else if(!this.editor.isChromelessView())if(mxUtils.hasScrollbars(b.container))if(b.pageVisible){var e=b.getPagePadding();b.container.scrollTop=Math.floor(e.y-this.editor.initialTopSpacing)-1;b.container.scrollLeft=Math.floor(Math.min(e.x,(b.container.scrollWidth-b.container.clientWidth)/2))-
1;e=b.getGraphBounds();0<e.width&&0<e.height&&(e.x>b.container.scrollLeft+.9*b.container.clientWidth&&(b.container.scrollLeft=Math.min(e.x+e.width-b.container.clientWidth,e.x-10)),e.y>b.container.scrollTop+.9*b.container.clientHeight&&(b.container.scrollTop=Math.min(e.y+e.height-b.container.clientHeight,e.y-10)))}else{e=b.getGraphBounds();var k=Math.max(e.width,b.scrollTileSize.width*b.view.scale);b.container.scrollTop=Math.floor(Math.max(0,e.y-Math.max(20,(b.container.clientHeight-Math.max(e.height,
b.scrollTileSize.height*b.view.scale))/4)));b.container.scrollLeft=Math.floor(Math.max(0,e.x-Math.max(0,(b.container.clientWidth-k)/2)))}else{e=mxRectangle.fromRectangle(b.pageVisible?b.view.getBackgroundPageBounds():b.getGraphBounds());k=b.view.translate;var l=b.view.scale;e.x=e.x/l-k.x;e.y=e.y/l-k.y;e.width/=l;e.height/=l;b.view.setTranslate(Math.floor(Math.max(0,(b.container.clientWidth-e.width)/2)-e.x+2),Math.floor((b.pageVisible?0:Math.max(0,(b.container.clientHeight-e.height)/4))-e.y+1))}};
EditorUi.prototype.setPageVisible=function(b){var e=this.editor.graph,k=mxUtils.hasScrollbars(e.container),l=0,B=0;k&&(l=e.view.translate.x*e.view.scale-e.container.scrollLeft,B=e.view.translate.y*e.view.scale-e.container.scrollTop);e.pageVisible=b;e.pageBreaksVisible=b;e.preferPageSize=b;e.view.validateBackground();if(k){var q=e.getSelectionCells();e.clearSelection();e.setSelectionCells(q)}e.sizeDidChange();k&&(e.container.scrollLeft=e.view.translate.x*e.view.scale-l,e.container.scrollTop=e.view.translate.y*
e.view.scale-B);e.defaultPageVisible=b;this.fireEvent(new mxEventObject("pageViewChanged"))};
EditorUi.prototype.installResizeHandler=function(b,e,k){e&&(b.window.setSize=function(B,q){if(!this.minimized){var D=window.innerHeight||document.body.clientHeight||document.documentElement.clientHeight;B=Math.min(B,(window.innerWidth||document.body.clientWidth||document.documentElement.clientWidth)-this.getX());q=Math.min(q,D-this.getY())}mxWindow.prototype.setSize.apply(this,arguments)});b.window.setLocation=function(B,q){var D=window.innerWidth||document.body.clientWidth||document.documentElement.clientWidth,
N=window.innerHeight||document.body.clientHeight||document.documentElement.clientHeight,S=parseInt(this.div.style.width),F=parseInt(this.div.style.height);B=Math.max(0,Math.min(B,D-S));q=Math.max(0,Math.min(q,N-F));this.getX()==B&&this.getY()==q||mxWindow.prototype.setLocation.apply(this,arguments);e&&!this.minimized&&this.setSize(S,F)};var l=mxUtils.bind(this,function(){var B=b.window.getX(),q=b.window.getY();b.window.setLocation(B,q)});mxEvent.addListener(window,"resize",l);b.destroy=function(){mxEvent.removeListener(window,
"resize",l);b.window.destroy();null!=k&&k()}};function ChangeGridColor(b,e){this.ui=b;this.color=e}ChangeGridColor.prototype.execute=function(){var b=this.ui.editor.graph.view.gridColor;this.ui.setGridColor(this.color);this.color=b};(function(){var b=new mxObjectCodec(new ChangeGridColor,["ui"]);mxCodecRegistry.register(b)})();
function ChangePageSetup(b,e,k,l,B){this.ui=b;this.previousColor=this.color=e;this.previousImage=this.image=k;this.previousFormat=this.format=l;this.previousPageScale=this.pageScale=B;this.ignoreImage=this.ignoreColor=!1}
ChangePageSetup.prototype.execute=function(){var b=this.ui.editor.graph;if(!this.ignoreColor){this.color=this.previousColor;var e=b.background;this.ui.setBackgroundColor(this.previousColor);this.previousColor=e}if(!this.ignoreImage){this.image=this.previousImage;e=b.backgroundImage;var k=this.previousImage;null!=k&&null!=k.src&&"data:page/id,"==k.src.substring(0,13)&&(k=this.ui.createImageForPageLink(k.src,this.ui.currentPage));this.ui.setBackgroundImage(k);this.previousImage=e}null!=this.previousFormat&&
(this.format=this.previousFormat,e=b.pageFormat,this.previousFormat.width!=e.width||this.previousFormat.height!=e.height)&&(this.ui.setPageFormat(this.previousFormat),this.previousFormat=e);null!=this.foldingEnabled&&this.foldingEnabled!=this.ui.editor.graph.foldingEnabled&&(this.ui.setFoldingEnabled(this.foldingEnabled),this.foldingEnabled=!this.foldingEnabled);null!=this.previousPageScale&&(b=this.ui.editor.graph.pageScale,this.previousPageScale!=b&&(this.ui.setPageScale(this.previousPageScale),
this.previousPageScale=b))};(function(){var b=new mxObjectCodec(new ChangePageSetup,["ui","previousColor","previousImage","previousFormat","previousPageScale"]);b.afterDecode=function(e,k,l){l.previousColor=l.color;l.previousImage=l.image;l.previousFormat=l.format;l.previousPageScale=l.pageScale;null!=l.foldingEnabled&&(l.foldingEnabled=!l.foldingEnabled);return l};mxCodecRegistry.register(b)})();
EditorUi.prototype.setBackgroundColor=function(b){this.editor.graph.background=b;this.editor.graph.view.validateBackground();this.fireEvent(new mxEventObject("backgroundColorChanged"))};EditorUi.prototype.setFoldingEnabled=function(b){this.editor.graph.foldingEnabled=b;this.editor.graph.view.revalidate();this.fireEvent(new mxEventObject("foldingEnabledChanged"))};
EditorUi.prototype.setPageFormat=function(b,e){e=null!=e?e:"1"==urlParams.sketch;this.editor.graph.pageFormat=b;e||(this.editor.graph.pageVisible?(this.editor.graph.view.validateBackground(),this.editor.graph.sizeDidChange()):this.actions.get("pageView").funct());this.fireEvent(new mxEventObject("pageFormatChanged"))};
EditorUi.prototype.setPageScale=function(b){this.editor.graph.pageScale=b;this.editor.graph.pageVisible?(this.editor.graph.view.validateBackground(),this.editor.graph.sizeDidChange()):this.actions.get("pageView").funct();this.fireEvent(new mxEventObject("pageScaleChanged"))};EditorUi.prototype.setGridColor=function(b){this.editor.graph.view.gridColor=b;this.editor.graph.view.validateBackground();this.fireEvent(new mxEventObject("gridColorChanged"))};
EditorUi.prototype.addUndoListener=function(){var b=this.actions.get("undo"),e=this.actions.get("redo"),k=this.editor.undoManager,l=mxUtils.bind(this,function(){b.setEnabled(this.canUndo());e.setEnabled(this.canRedo())});k.addListener(mxEvent.ADD,l);k.addListener(mxEvent.UNDO,l);k.addListener(mxEvent.REDO,l);k.addListener(mxEvent.CLEAR,l);var B=this.editor.graph.cellEditor.startEditing;this.editor.graph.cellEditor.startEditing=function(){B.apply(this,arguments);l()};var q=this.editor.graph.cellEditor.stopEditing;
this.editor.graph.cellEditor.stopEditing=function(D,N){q.apply(this,arguments);l()};l()};
EditorUi.prototype.updateActionStates=function(){for(var b=this.editor.graph,e=this.getSelectionState(),k=b.isEnabled()&&!b.isCellLocked(b.getDefaultParent()),l="cut copy bold italic underline delete duplicate editStyle editTooltip editLink backgroundColor borderColor edit toFront toBack solid dashed pasteSize dotted fillColor gradientColor shadow fontColor formattedText rounded toggleRounded strokeColor sharp snapToGrid".split(" "),B=0;B<l.length;B++)this.actions.get(l[B]).setEnabled(0<e.cells.length);
this.actions.get("grid").setEnabled(!this.editor.chromeless||this.editor.editable);this.actions.get("pasteSize").setEnabled(null!=this.copiedSize&&0<e.vertices.length);this.actions.get("pasteData").setEnabled(null!=this.copiedValue&&0<e.cells.length);this.actions.get("setAsDefaultStyle").setEnabled(1==b.getSelectionCount());this.actions.get("lockUnlock").setEnabled(!b.isSelectionEmpty());this.actions.get("bringForward").setEnabled(1==e.cells.length);this.actions.get("sendBackward").setEnabled(1==
e.cells.length);this.actions.get("rotation").setEnabled(1==e.vertices.length);this.actions.get("wordWrap").setEnabled(1==e.vertices.length);this.actions.get("autosize").setEnabled(0<e.vertices.length);this.actions.get("copySize").setEnabled(1==e.vertices.length);this.actions.get("clearWaypoints").setEnabled(e.connections);this.actions.get("curved").setEnabled(0<e.edges.length);this.actions.get("turn").setEnabled(0<e.cells.length);this.actions.get("group").setEnabled(!e.row&&!e.cell&&(1<e.cells.length||
1==e.vertices.length&&0==b.model.getChildCount(e.cells[0])&&!b.isContainer(e.vertices[0])));this.actions.get("ungroup").setEnabled(!e.row&&!e.cell&&!e.table&&0<e.vertices.length&&(b.isContainer(e.vertices[0])||0<b.getModel().getChildCount(e.vertices[0])));this.actions.get("removeFromGroup").setEnabled(1==e.cells.length&&b.getModel().isVertex(b.getModel().getParent(e.cells[0])));this.actions.get("collapsible").setEnabled(1==e.vertices.length&&(0<b.model.getChildCount(e.vertices[0])||b.isContainer(e.vertices[0])));
this.actions.get("exitGroup").setEnabled(null!=b.view.currentRoot);this.actions.get("home").setEnabled(null!=b.view.currentRoot);this.actions.get("enterGroup").setEnabled(1==e.cells.length&&b.isValidRoot(e.cells[0]));this.actions.get("editLink").setEnabled(1==e.cells.length);this.actions.get("openLink").setEnabled(1==e.cells.length&&null!=b.getLinkForCell(e.cells[0]));this.actions.get("guides").setEnabled(b.isEnabled());this.actions.get("selectVertices").setEnabled(k);this.actions.get("selectEdges").setEnabled(k);
this.actions.get("selectAll").setEnabled(k);this.actions.get("selectNone").setEnabled(k);l=1==e.vertices.length&&b.isCellFoldable(e.vertices[0]);this.actions.get("expand").setEnabled(l);this.actions.get("collapse").setEnabled(l);this.menus.get("navigation").setEnabled(0<e.cells.length||null!=b.view.currentRoot);this.menus.get("layout").setEnabled(k);this.menus.get("insert").setEnabled(k);this.menus.get("direction").setEnabled(e.unlocked&&1==e.vertices.length);this.menus.get("distribute").setEnabled(e.unlocked&&
1<e.vertices.length);this.menus.get("align").setEnabled(e.unlocked&&0<e.cells.length);this.updatePasteActionStates()};EditorUi.prototype.zeroOffset=new mxPoint(0,0);EditorUi.prototype.getDiagramContainerOffset=function(){return this.zeroOffset};
EditorUi.prototype.refresh=function(b){b=null!=b?b:!0;var e=this.container.clientWidth,k=this.container.clientHeight;this.container==document.body&&(e=document.body.clientWidth||document.documentElement.clientWidth,k=document.documentElement.clientHeight);var l=0;mxClient.IS_IOS&&!window.navigator.standalone&&"undefined"!==typeof Menus&&window.innerHeight!=document.documentElement.clientHeight&&(l=document.documentElement.clientHeight-window.innerHeight,window.scrollTo(0,0));var B=Math.max(0,Math.min(this.hsplitPosition,
e-this.splitSize-20));e=0;null!=this.menubar&&(this.menubarContainer.style.height=this.menubarHeight+"px",e+=this.menubarHeight);null!=this.toolbar&&(this.toolbarContainer.style.top=this.menubarHeight+"px",this.toolbarContainer.style.height=this.toolbarHeight+"px",e+=this.toolbarHeight);0<e&&(e+=1);var q=0;if(null!=this.sidebarFooterContainer){var D=this.footerHeight+l;q=Math.max(0,Math.min(k-e-D,this.sidebarFooterHeight));this.sidebarFooterContainer.style.width=B+"px";this.sidebarFooterContainer.style.height=
q+"px";this.sidebarFooterContainer.style.bottom=D+"px"}k=null!=this.format?this.formatWidth:0;this.sidebarContainer.style.top=e+"px";this.sidebarContainer.style.width=B+"px";this.formatContainer.style.top=e+"px";this.formatContainer.style.width=k+"px";this.formatContainer.style.display=null!=this.format?"":"none";D=this.getDiagramContainerOffset();var N=null!=this.hsplit.parentNode?B+this.splitSize:0;this.footerContainer.style.height=this.footerHeight+"px";this.hsplit.style.top=this.sidebarContainer.style.top;
this.hsplit.style.bottom=this.footerHeight+l+"px";this.hsplit.style.left=B+"px";this.footerContainer.style.display=0==this.footerHeight?"none":"";null!=this.tabContainer&&(this.tabContainer.style.left=N+"px");0<this.footerHeight&&(this.footerContainer.style.bottom=l+"px");B=0;null!=this.tabContainer&&(this.tabContainer.style.bottom=this.footerHeight+l+"px",this.tabContainer.style.right=k+"px",B=this.tabContainer.clientHeight);this.sidebarContainer.style.bottom=this.footerHeight+q+l+"px";this.formatContainer.style.bottom=
this.footerHeight+l+"px";this.diagramContainer.style.left=N+D.x+"px";this.diagramContainer.style.top=e+D.y+"px";this.diagramContainer.style.right=k+"px";this.diagramContainer.style.bottom=this.footerHeight+l+B+"px";b&&this.editor.graph.sizeDidChange()};EditorUi.prototype.createTabContainer=function(){return null};
EditorUi.prototype.createDivs=function(){this.menubarContainer=this.createDiv("geMenubarContainer");this.toolbarContainer=this.createDiv("geToolbarContainer");this.sidebarContainer=this.createDiv("geSidebarContainer");this.formatContainer=this.createDiv("geSidebarContainer geFormatContainer");this.diagramContainer=this.createDiv("geDiagramContainer");this.footerContainer=this.createDiv("geFooterContainer");this.hsplit=this.createDiv("geHsplit");this.hsplit.setAttribute("title",mxResources.get("collapseExpand"));
this.menubarContainer.style.top="0px";this.menubarContainer.style.left="0px";this.menubarContainer.style.right="0px";this.toolbarContainer.style.left="0px";this.toolbarContainer.style.right="0px";this.sidebarContainer.style.left="0px";this.formatContainer.style.right="0px";this.formatContainer.style.zIndex="1";this.diagramContainer.style.right=(null!=this.format?this.formatWidth:0)+"px";this.footerContainer.style.left="0px";this.footerContainer.style.right="0px";this.footerContainer.style.bottom=
"0px";this.footerContainer.style.zIndex=mxPopupMenu.prototype.zIndex-3;this.hsplit.style.width=this.splitSize+"px";this.sidebarFooterContainer=this.createSidebarFooterContainer();null!=this.sidebarFooterContainer&&(this.sidebarFooterContainer.style.left="0px");this.editor.chromeless?this.diagramContainer.style.border="none":this.tabContainer=this.createTabContainer()};
EditorUi.prototype.createSidebarContainer=function(){var b=document.createElement("div");b.className="geSidebarContainer";b.style.position="absolute";b.style.width="100%";b.style.height="100%";b.style.border="1px solid whiteSmoke";b.style.overflowX="hidden";b.style.overflowY="auto";return b};EditorUi.prototype.createSidebarFooterContainer=function(){return null};
EditorUi.prototype.createUi=function(){this.menubar=this.editor.chromeless?null:this.menus.createMenubar(this.createDiv("geMenubar"));null!=this.menubar&&this.menubarContainer.appendChild(this.menubar.container);null!=this.menubar&&(this.statusContainer=this.createStatusContainer(),this.editor.addListener("statusChanged",mxUtils.bind(this,function(){this.setStatusText(this.editor.getStatus())})),this.setStatusText(this.editor.getStatus()),this.menubar.container.appendChild(this.statusContainer),this.container.appendChild(this.menubarContainer));
this.sidebar=this.editor.chromeless?null:this.createSidebar(this.sidebarContainer);null!=this.sidebar&&this.container.appendChild(this.sidebarContainer);this.format=this.editor.chromeless||!this.formatEnabled?null:this.createFormat(this.formatContainer);null!=this.format&&this.container.appendChild(this.formatContainer);var b=this.editor.chromeless?null:this.createFooter();null!=b&&(this.footerContainer.appendChild(b),this.container.appendChild(this.footerContainer));null!=this.sidebar&&null!=this.sidebarFooterContainer&&
this.container.appendChild(this.sidebarFooterContainer);this.container.appendChild(this.diagramContainer);null!=this.container&&null!=this.tabContainer&&this.container.appendChild(this.tabContainer);this.toolbar=this.editor.chromeless?null:this.createToolbar(this.createDiv("geToolbar"));null!=this.toolbar&&(this.toolbarContainer.appendChild(this.toolbar.container),this.container.appendChild(this.toolbarContainer));null!=this.sidebar&&(this.container.appendChild(this.hsplit),this.addSplitHandler(this.hsplit,
!0,0,mxUtils.bind(this,function(e){this.hsplitPosition=e;this.refresh()})))};
EditorUi.prototype.createStatusContainer=function(){var b=document.createElement("a");b.className="geItem geStatus";b.style.display="inline-flex";b.style.alignItems="center";mxEvent.addListener(b,"click",mxUtils.bind(this,function(e){var k=mxEvent.getSource(e);if("A"!=k.nodeName){var l=k.getAttribute("data-action");if("statusFunction"==l&&null!=this.editor.statusFunction)this.editor.statusFunction();else if(null!=l)k=this.actions.get(l),null!=k&&k.funct();else{l=k.getAttribute("data-title");var B=
k.getAttribute("data-message");null!=l&&null!=B?this.showError(l,B):(k=k.getAttribute("data-link"),null!=k&&this.editor.graph.openLink(k))}mxEvent.consume(e)}}));return b};
EditorUi.prototype.setStatusText=function(b){this.statusContainer.innerHTML=b;0==this.statusContainer.getElementsByTagName("div").length&&null!=b&&0<b.length&&(this.statusContainer.innerText="",b=this.createStatusDiv(b),this.statusContainer.appendChild(b));b=this.statusContainer.querySelectorAll('[data-effect="fade"]');if(null!=b)for(var e=0;e<b.length;e++)(function(k){mxUtils.setOpacity(k,0);mxUtils.setPrefixedStyle(k.style,"transform","scaleX(0)");mxUtils.setPrefixedStyle(k.style,"transition","all 0.2s ease");
window.setTimeout(mxUtils.bind(this,function(){mxUtils.setOpacity(k,100);mxUtils.setPrefixedStyle(k.style,"transform","scaleX(1)");mxUtils.setPrefixedStyle(k.style,"transition","all 1s ease");window.setTimeout(mxUtils.bind(this,function(){mxUtils.setPrefixedStyle(k.style,"transform","scaleX(0)");mxUtils.setOpacity(k,0);window.setTimeout(mxUtils.bind(this,function(){null!=k.parentNode&&k.parentNode.removeChild(k)}),1E3)}),Editor.updateStatusInterval/2)}),0)})(b[e])};
EditorUi.prototype.createStatusDiv=function(b){var e=document.createElement("div");e.setAttribute("title",b);e.innerHTML=b;return e};EditorUi.prototype.createToolbar=function(b){return new Toolbar(this,b)};EditorUi.prototype.createSidebar=function(b){return new Sidebar(this,b)};EditorUi.prototype.createFormat=function(b){return new Format(this,b)};EditorUi.prototype.createFooter=function(){return this.createDiv("geFooter")};
EditorUi.prototype.createDiv=function(b){var e=document.createElement("div");e.className=b;return e};
EditorUi.prototype.addSplitHandler=function(b,e,k,l){function B(R){if(null!=D){var d=new mxPoint(mxEvent.getClientX(R),mxEvent.getClientY(R));l(Math.max(0,N+(e?d.x-D.x:D.y-d.y)-k));mxEvent.consume(R);N!=K()&&(S=!0,F=null)}}function q(R){B(R);D=N=null}var D=null,N=null,S=!0,F=null;mxClient.IS_POINTER&&(b.style.touchAction="none");var K=mxUtils.bind(this,function(){var R=parseInt(e?b.style.left:b.style.bottom);e||(R=R+k-this.footerHeight);return R});mxEvent.addGestureListeners(b,function(R){D=new mxPoint(mxEvent.getClientX(R),
mxEvent.getClientY(R));N=K();S=!1;mxEvent.consume(R)});mxEvent.addListener(b,"click",mxUtils.bind(this,function(R){if(!S&&this.hsplitClickEnabled){var d=null!=F?F-k:0;F=K();l(d);mxEvent.consume(R)}}));mxEvent.addGestureListeners(document,null,B,q);this.destroyFunctions.push(function(){mxEvent.removeGestureListeners(document,null,B,q)})};
EditorUi.prototype.prompt=function(b,e,k){b=new FilenameDialog(this,e,mxResources.get("apply"),function(l){k(parseFloat(l))},b);this.showDialog(b.container,300,80,!0,!0);b.init()};
EditorUi.prototype.handleError=function(b,e,k,l,B){b=null!=b&&null!=b.error?b.error:b;if(null!=b||null!=e){B=mxUtils.htmlEntities(mxResources.get("unknownError"));var q=mxResources.get("ok");e=null!=e?e:mxResources.get("error");null!=b&&null!=b.message&&(B=mxUtils.htmlEntities(b.message));this.showError(e,B,q,k,null,null,null,null,null,null,null,null,l?k:null)}else null!=k&&k()};
EditorUi.prototype.showError=function(b,e,k,l,B,q,D,N,S,F,K,R,d){b=new ErrorDialog(this,b,e,k||mxResources.get("ok"),l,B,q,D,R,N,S);e=Math.ceil(null!=e?e.length/50:1);this.showDialog(b.container,F||340,K||100+20*e,!0,!1,d);b.init()};EditorUi.prototype.showDialog=function(b,e,k,l,B,q,D,N,S,F){this.editor.graph.tooltipHandler.resetTimer();this.editor.graph.tooltipHandler.hideTooltip();null==this.dialogs&&(this.dialogs=[]);this.dialog=new Dialog(this,b,e,k,l,B,q,D,N,S,F);this.dialogs.push(this.dialog)};
EditorUi.prototype.hideDialog=function(b,e,k){null!=this.dialogs&&0<this.dialogs.length&&(null==k||k==this.dialog.container.firstChild)&&(k=this.dialogs.pop(),0==k.close(b,e)?this.dialogs.push(k):(this.dialog=0<this.dialogs.length?this.dialogs[this.dialogs.length-1]:null,this.editor.fireEvent(new mxEventObject("hideDialog")),null==this.dialog&&"hidden"!=this.editor.graph.container.style.visibility&&window.setTimeout(mxUtils.bind(this,function(){this.editor.graph.isEditing()&&null!=this.editor.graph.cellEditor.textarea?
this.editor.graph.cellEditor.textarea.focus():(mxUtils.clearSelection(),this.editor.graph.container.focus())}),0)))};EditorUi.prototype.ctrlEnter=function(){var b=this.editor.graph;if(b.isEnabled())try{for(var e=b.getSelectionCells(),k=new mxDictionary,l=[],B=0;B<e.length;B++){var q=b.isTableCell(e[B])?b.model.getParent(e[B]):e[B];null==q||k.get(q)||(k.put(q,!0),l.push(q))}b.setSelectionCells(b.duplicateCells(l,!1))}catch(D){this.handleError(D)}};
EditorUi.prototype.pickColor=function(b,e){var k=this.editor.graph,l=k.cellEditor.saveSelection(),B=230+17*(Math.ceil(ColorDialog.prototype.presetColors.length/12)+Math.ceil(ColorDialog.prototype.defaultColors.length/12));b=new ColorDialog(this,mxUtils.rgba2hex(b)||"none",function(q){k.cellEditor.restoreSelection(l);e(q)},function(){k.cellEditor.restoreSelection(l)});this.showDialog(b.container,230,B,!0,!1);b.init()};
EditorUi.prototype.openFile=function(){window.openFile=new OpenFile(mxUtils.bind(this,function(b){this.hideDialog(b)}));this.showDialog((new OpenDialog(this)).container,Editor.useLocalStorage?640:320,Editor.useLocalStorage?480:220,!0,!0,function(){window.openFile=null})};
EditorUi.prototype.extractGraphModelFromHtml=function(b){var e=null;try{var k=b.indexOf("&lt;mxGraphModel ");if(0<=k){var l=b.lastIndexOf("&lt;/mxGraphModel&gt;");l>k&&(e=b.substring(k,l+21).replace(/&gt;/g,">").replace(/&lt;/g,"<").replace(/\\&quot;/g,'"').replace(/\n/g,""))}}catch(B){}return e};
EditorUi.prototype.readGraphModelFromClipboard=function(b){this.readGraphModelFromClipboardWithType(mxUtils.bind(this,function(e){null!=e?b(e):this.readGraphModelFromClipboardWithType(mxUtils.bind(this,function(k){if(null!=k){var l=decodeURIComponent(k);this.isCompatibleString(l)&&(k=l)}b(k)}),"text")}),"html")};
EditorUi.prototype.readGraphModelFromClipboardWithType=function(b,e){navigator.clipboard.read().then(mxUtils.bind(this,function(k){if(null!=k&&0<k.length&&"html"==e&&0<=mxUtils.indexOf(k[0].types,"text/html"))k[0].getType("text/html").then(mxUtils.bind(this,function(l){l.text().then(mxUtils.bind(this,function(B){try{var q=this.parseHtmlData(B),D="text/plain"!=q.getAttribute("data-type")?q.innerHTML:mxUtils.trim(null==q.innerText?mxUtils.getTextContent(q):q.innerText);try{var N=D.lastIndexOf("%3E");
0<=N&&N<D.length-3&&(D=D.substring(0,N+3))}catch(K){}try{var S=q.getElementsByTagName("span"),F=null!=S&&0<S.length?mxUtils.trim(decodeURIComponent(S[0].textContent)):decodeURIComponent(D);this.isCompatibleString(F)&&(D=F)}catch(K){}}catch(K){}b(this.isCompatibleString(D)?D:null)}))["catch"](function(B){b(null)})}))["catch"](function(l){b(null)});else if(null!=k&&0<k.length&&"text"==e&&0<=mxUtils.indexOf(k[0].types,"text/plain"))k[0].getType("text/plain").then(function(l){l.text().then(function(B){b(B)})["catch"](function(){b(null)})})["catch"](function(){b(null)});
else b(null)}))["catch"](function(k){b(null)})};
EditorUi.prototype.parseHtmlData=function(b){var e=null;if(null!=b&&0<b.length){var k="<meta "==b.substring(0,6);e=document.createElement("div");e.innerHTML=(k?'<meta charset="utf-8">':"")+this.editor.graph.sanitizeHtml(b);asHtml=!0;b=e.getElementsByTagName("style");if(null!=b)for(;0<b.length;)b[0].parentNode.removeChild(b[0]);null!=e.firstChild&&e.firstChild.nodeType==mxConstants.NODETYPE_ELEMENT&&null!=e.firstChild.nextSibling&&e.firstChild.nextSibling.nodeType==mxConstants.NODETYPE_ELEMENT&&"META"==
e.firstChild.nodeName&&"A"==e.firstChild.nextSibling.nodeName&&null==e.firstChild.nextSibling.nextSibling&&(b=null==e.firstChild.nextSibling.innerText?mxUtils.getTextContent(e.firstChild.nextSibling):e.firstChild.nextSibling.innerText,b==e.firstChild.nextSibling.getAttribute("href")&&(mxUtils.setTextContent(e,b),asHtml=!1));k=k&&null!=e.firstChild?e.firstChild.nextSibling:e.firstChild;null!=k&&null==k.nextSibling&&k.nodeType==mxConstants.NODETYPE_ELEMENT&&"IMG"==k.nodeName?(b=k.getAttribute("src"),
null!=b&&(Editor.isPngDataUrl(b)&&(k=Editor.extractGraphModelFromPng(b),null!=k&&0<k.length&&(b=k)),mxUtils.setTextContent(e,b),asHtml=!1)):(k=e.getElementsByTagName("img"),1==k.length&&(k=k[0],b=k.getAttribute("src"),null!=b&&k.parentNode==e&&1==e.children.length&&(Editor.isPngDataUrl(b)&&(k=Editor.extractGraphModelFromPng(b),null!=k&&0<k.length&&(b=k)),mxUtils.setTextContent(e,b),asHtml=!1)));asHtml&&Graph.removePasteFormatting(e)}asHtml||e.setAttribute("data-type","text/plain");return e};
EditorUi.prototype.extractGraphModelFromEvent=function(b){var e=null,k=null;null!=b&&(b=null!=b.dataTransfer?b.dataTransfer:b.clipboardData,null!=b&&(10==document.documentMode||11==document.documentMode?k=b.getData("Text"):(k=0<=mxUtils.indexOf(b.types,"text/html")?b.getData("text/html"):null,0<=mxUtils.indexOf(b.types,"text/plain")&&(null==k||0==k.length)&&(k=b.getData("text/plain"))),null!=k&&(k=Graph.zapGremlins(mxUtils.trim(k)),b=this.extractGraphModelFromHtml(k),null!=b&&(k=b))));null!=k&&this.isCompatibleString(k)&&
(e=k);return e};EditorUi.prototype.isCompatibleString=function(b){return!1};EditorUi.prototype.saveFile=function(b){b||null==this.editor.filename?(b=new FilenameDialog(this,this.editor.getOrCreateFilename(),mxResources.get("save"),mxUtils.bind(this,function(e){this.save(e)}),null,mxUtils.bind(this,function(e){if(null!=e&&0<e.length)return!0;mxUtils.confirm(mxResources.get("invalidName"));return!1})),this.showDialog(b.container,300,100,!0,!0),b.init()):this.save(this.editor.getOrCreateFilename())};
EditorUi.prototype.save=function(b){if(null!=b){this.editor.graph.isEditing()&&this.editor.graph.stopEditing();var e=mxUtils.getXml(this.editor.getGraphXml());try{if(Editor.useLocalStorage){if(null!=localStorage.getItem(b)&&!mxUtils.confirm(mxResources.get("replaceIt",[b])))return;localStorage.setItem(b,e);this.editor.setStatus(mxUtils.htmlEntities(mxResources.get("saved"))+" "+new Date)}else if(e.length<MAX_REQUEST_SIZE)(new mxXmlRequest(SAVE_URL,"filename="+encodeURIComponent(b)+"&xml="+encodeURIComponent(e))).simulate(document,
"_blank");else{mxUtils.alert(mxResources.get("drawingTooLarge"));mxUtils.popup(e);return}this.editor.setModified(!1);this.editor.setFilename(b);this.updateDocumentTitle()}catch(k){this.editor.setStatus(mxUtils.htmlEntities(mxResources.get("errorSavingFile")))}}};
EditorUi.prototype.executeLayouts=function(b,e){this.executeLayout(mxUtils.bind(this,function(){var k=new mxCompositeLayout(this.editor.graph,b),l=this.editor.graph.getSelectionCells();k.execute(this.editor.graph.getDefaultParent(),0==l.length?null:l)}),!0,e)};
EditorUi.prototype.executeLayout=function(b,e,k){var l=this.editor.graph;l.getModel().beginUpdate();try{b()}catch(B){throw B;}finally{this.allowAnimation&&e&&l.isEnabled()?(b=new mxMorphing(l),b.addListener(mxEvent.DONE,mxUtils.bind(this,function(){l.getModel().endUpdate();null!=k&&k()})),b.startAnimation()):(l.getModel().endUpdate(),null!=k&&k())}};