EditorUi.prototype.createShapePicker=function(a,b,f,e,g,d,h,n,u){var m=this.editor.graph,r=null;u=null!=u?u:function(C){C=C[0];var F=0,H=0;null!=C.geometry&&(F=C.geometry.width/2,H=C.geometry.height/2);return new mxPoint(m.snap(Math.round(a/m.view.scale)-m.view.translate.x-F),m.snap(Math.round(b/m.view.scale)-m.view.translate.y-H))};if(null!=h&&0<h.length){var x=this;m=this.editor.graph;r=document.createElement("div");g=m.view.getState(f);var B=null==f||null!=g&&m.isTransparentState(g)?null:m.copyStyle(f);
f=6>h.length?35*h.length:140;r.className="geToolbarContainer geSidebarContainer";r.style.cssText="position:absolute;left:"+a+"px;top:"+b+"px;width:"+f+"px;border-radius:10px;padding:4px;text-align:center;box-shadow:0px 0px 3px 1px #d1d1d1;padding: 6px 0 8px 0;z-index: "+mxPopupMenu.prototype.zIndex+1+";";n||mxUtils.setPrefixedStyle(r.style,"transform","translate(-22px,-22px)");null!=m.background&&m.background!=mxConstants.NONE&&(r.style.backgroundColor=m.background);m.container.appendChild(r);f=mxUtils.bind(this,
function(C){var F=document.createElement("a");F.className="geItem";F.style.cssText="position:relative;display:inline-block;position:relative;width:30px;height:30px;cursor:pointer;overflow:hidden;padding:1px";r.appendChild(F);null!=B&&"1"!=urlParams.sketch?this.sidebar.graph.pasteStyle(B,[C]):x.insertHandler([C],""!=C.value&&"1"!=urlParams.sketch,this.sidebar.graph.model);F.appendChild(this.sidebar.createVertexTemplateFromCells([C],C.geometry.width,C.geometry.height,"",!0,!1,null,!1,mxUtils.bind(this,
function(H){var E=m.cloneCell(C);if(null!=e)e(E);else{var N=u([E]);E.geometry.x=N.x;E.geometry.y=N.y;m.model.beginUpdate();try{m.addCell(E),m.model.isVertex(E)&&m.isAutoSizeCell(E)&&m.updateCellSize(E)}finally{m.model.endUpdate()}m.setSelectionCell(E);m.scrollCellToVisible(E);m.startEditingAtCell(E);null!=x.hoverIcons&&x.hoverIcons.update(m.view.getState(E))}null!=d&&d();mxEvent.consume(H)}),25,25))});for(g=0;g<(n?Math.min(h.length,4):h.length);g++)f(h[g]);h=r.offsetTop+r.clientHeight-(m.container.scrollTop+
m.container.offsetHeight);0<h&&(r.style.top=Math.max(m.container.scrollTop+22,b-h)+"px");h=r.offsetLeft+r.clientWidth-(m.container.scrollLeft+m.container.offsetWidth);0<h&&(r.style.left=Math.max(m.container.scrollLeft+22,a-h)+"px")}return r};
EditorUi.prototype.getCellsForShapePicker=function(a,b){b=mxUtils.bind(this,function(f,e,g,d){return this.editor.graph.createVertex(null,null,d||"",0,0,e||120,g||60,f,!1)});return[null!=a?this.editor.graph.cloneCell(a):b("text;html=1;align=center;verticalAlign=middle;resizable=0;points=[];autosize=1;strokeColor=none;fillColor=none;",40,20,"Text"),b("whiteSpace=wrap;html=1;"),b("ellipse;whiteSpace=wrap;html=1;"),b("rhombus;whiteSpace=wrap;html=1;",80,80),b("rounded=1;whiteSpace=wrap;html=1;"),b("shape=parallelogram;perimeter=parallelogramPerimeter;whiteSpace=wrap;html=1;fixedSize=1;"),
b("shape=trapezoid;perimeter=trapezoidPerimeter;whiteSpace=wrap;html=1;fixedSize=1;",120,60),b("shape=hexagon;perimeter=hexagonPerimeter2;whiteSpace=wrap;html=1;fixedSize=1;",120,80),b("shape=step;perimeter=stepPerimeter;whiteSpace=wrap;html=1;fixedSize=1;",120,80),b("shape=process;whiteSpace=wrap;html=1;backgroundOutline=1;"),b("triangle;whiteSpace=wrap;html=1;",60,80),b("shape=document;whiteSpace=wrap;html=1;boundedLbl=1;",120,80),b("shape=tape;whiteSpace=wrap;html=1;",120,100),b("ellipse;shape=cloud;whiteSpace=wrap;html=1;",
120,80),b("shape=singleArrow;whiteSpace=wrap;html=1;arrowWidth=0.4;arrowSize=0.4;",80,60),b("shape=waypoint;sketch=0;size=6;pointerEvents=1;points=[];fillColor=none;resizable=0;rotatable=0;perimeter=centerPerimeter;snapToPoint=1;",40,40)]};EditorUi.prototype.hideShapePicker=function(a){null!=this.shapePicker&&(this.shapePicker.parentNode.removeChild(this.shapePicker),this.shapePicker=null,a||null==this.shapePickerCallback||this.shapePickerCallback(),this.shapePickerCallback=null)};
EditorUi.prototype.onKeyDown=function(a){var b=this.editor.graph;if(9==a.which&&b.isEnabled()&&!mxEvent.isControlDown(a)){if(b.isEditing())if(mxEvent.isAltDown(a))b.stopEditing(!1);else try{var f=b.cellEditor.isContentEditing()&&b.cellEditor.isTextSelected();if(window.getSelection&&b.cellEditor.isContentEditing()&&!f&&!mxClient.IS_IE&&!mxClient.IS_IE11){var e=window.getSelection(),g=0<e.rangeCount?e.getRangeAt(0).commonAncestorContainer:null;f=null!=g&&("LI"==g.nodeName||null!=g.parentNode&&"LI"==
g.parentNode.nodeName)}f?document.execCommand(mxEvent.isShiftDown(a)?"outdent":"indent",!1,null):mxEvent.isShiftDown(a)?b.stopEditing(!1):b.cellEditor.insertTab(b.cellEditor.isContentEditing()?null:4)}catch(d){}else mxEvent.isAltDown(a)?b.selectParentCell():b.selectCell(!mxEvent.isShiftDown(a));mxEvent.consume(a)}};
EditorUi.prototype.onKeyPress=function(a){var b=this.editor.graph;!this.isImmediateEditingEvent(a)||b.isEditing()||b.isSelectionEmpty()||0===a.which||27===a.which||mxEvent.isAltDown(a)||mxEvent.isControlDown(a)||mxEvent.isMetaDown(a)||(b.escape(),b.startEditing(),mxClient.IS_FF&&(b=b.cellEditor,null!=b.textarea&&(b.textarea.innerHTML=String.fromCharCode(a.which),a=document.createRange(),a.selectNodeContents(b.textarea),a.collapse(!1),b=window.getSelection(),b.removeAllRanges(),b.addRange(a))))};
EditorUi.prototype.isImmediateEditingEvent=function(a){return!0};
EditorUi.prototype.updateCssForMarker=function(a,b,f,e,g){a.style.verticalAlign="top";a.style.height="21px";a.style.width="21px";a.innerText="";"flexArrow"==f?a.className=null!=e&&e!=mxConstants.NONE?"geSprite geSprite-"+b+"blocktrans":"geSprite geSprite-noarrow":(f=this.getImageForMarker(e,g),null!=f?(e=document.createElement("img"),e.className="geAdaptiveAsset",e.style.position="absolute",e.style.marginTop="0.5px",e.setAttribute("src",f),a.className="","end"==b&&mxUtils.setPrefixedStyle(e.style,
"transform","scaleX(-1)"),a.appendChild(e)):(a.className="geSprite geSprite-noarrow",a.innerHTML=mxUtils.htmlEntities(mxResources.get("none")),a.style.backgroundImage="none",a.style.verticalAlign="top",a.style.marginTop="4px",a.style.fontSize="10px",a.style.filter="none",a.style.color=this.defaultStrokeColor,a.nextSibling.style.marginTop="0px"))};
EditorUi.prototype.getImageForMarker=function(a,b){var f=null;a==mxConstants.ARROW_CLASSIC?f="1"!=b?Format.classicMarkerImage.src:Format.classicFilledMarkerImage.src:a==mxConstants.ARROW_CLASSIC_THIN?f="1"!=b?Format.classicThinMarkerImage.src:Format.openThinFilledMarkerImage.src:a==mxConstants.ARROW_OPEN?f=Format.openFilledMarkerImage.src:a==mxConstants.ARROW_OPEN_THIN?f=Format.openThinFilledMarkerImage.src:a==mxConstants.ARROW_BLOCK?f="1"!=b?Format.blockMarkerImage.src:Format.blockFilledMarkerImage.src:
a==mxConstants.ARROW_BLOCK_THIN?f="1"!=b?Format.blockThinMarkerImage.src:Format.blockThinFilledMarkerImage.src:a==mxConstants.ARROW_OVAL?f="1"!=b?Format.ovalMarkerImage.src:Format.ovalFilledMarkerImage.src:a==mxConstants.ARROW_DIAMOND?f="1"!=b?Format.diamondMarkerImage.src:Format.diamondFilledMarkerImage.src:a==mxConstants.ARROW_DIAMOND_THIN?f="1"!=b?Format.diamondThinMarkerImage.src:Format.diamondThinFilledMarkerImage.src:"doubleBlock"==a?f="1"!=b?Format.doubleBlockMarkerImage.src:Format.doubleBlockFilledMarkerImage.src:
"box"==a?f=Format.boxMarkerImage.src:"halfCircle"==a?f=Format.halfCircleMarkerImage.src:"openAsync"==a?f=Format.openAsyncFilledMarkerImage.src:"async"==a?f="1"!=b?Format.asyncMarkerImage.src:Format.asyncFilledMarkerImage.src:"dash"==a?f=Format.dashMarkerImage.src:"baseDash"==a?f=Format.baseDashMarkerImage.src:"cross"==a?f=Format.crossMarkerImage.src:"circle"==a?f=Format.circleMarkerImage.src:"circlePlus"==a?f=Format.circlePlusMarkerImage.src:"ERone"==a?f=Format.EROneMarkerImage.src:"ERmandOne"==a?
f=Format.ERmandOneMarkerImage.src:"ERmany"==a?f=Format.ERmanyMarkerImage.src:"ERoneToMany"==a?f=Format.ERoneToManyMarkerImage.src:"ERzeroToOne"==a?f=Format.ERzeroToOneMarkerImage.src:"ERzeroToMany"==a&&(f=Format.ERzeroToManyMarkerImage.src);return f};EditorUi.prototype.createMenus=function(){return null};
EditorUi.prototype.updatePasteActionStates=function(){var a=this.editor.graph,b=this.actions.get("paste"),f=this.actions.get("pasteHere");b.setEnabled(this.editor.graph.cellEditor.isContentEditing()||(!mxClient.IS_FF&&null!=navigator.clipboard||!mxClipboard.isEmpty())&&a.isEnabled()&&!a.isCellLocked(a.getDefaultParent()));f.setEnabled(b.isEnabled())};
EditorUi.prototype.initClipboard=function(){var a=this,b=mxClipboard.cut;mxClipboard.cut=function(d){d.cellEditor.isContentEditing()?document.execCommand("cut",!1,null):b.apply(this,arguments);a.updatePasteActionStates()};mxClipboard.copy=function(d){var h=null;if(d.cellEditor.isContentEditing())document.execCommand("copy",!1,null);else{h=h||d.getSelectionCells();h=d.getExportableCells(d.model.getTopmostCells(h));for(var n={},u=d.createCellLookup(h),m=d.cloneCells(h,null,n),r=new mxGraphModel,x=r.getChildAt(r.getRoot(),
0),B=0;B<m.length;B++){r.add(x,m[B]);var C=d.view.getState(h[B]);if(null!=C){var F=d.getCellGeometry(m[B]);null!=F&&F.relative&&!r.isEdge(h[B])&&null==u[mxObjectIdentity.get(r.getParent(h[B]))]&&(F.offset=null,F.relative=!1,F.x=C.x/C.view.scale-C.view.translate.x,F.y=C.y/C.view.scale-C.view.translate.y)}}d.updateCustomLinks(d.createCellMapping(n,u),m);mxClipboard.insertCount=1;mxClipboard.setCells(m)}a.updatePasteActionStates();return h};var f=mxClipboard.paste;mxClipboard.paste=function(d){var h=
null;d.cellEditor.isContentEditing()?document.execCommand("paste",!1,null):h=f.apply(this,arguments);a.updatePasteActionStates();return h};var e=this.editor.graph.cellEditor.startEditing;this.editor.graph.cellEditor.startEditing=function(){e.apply(this,arguments);a.updatePasteActionStates()};var g=this.editor.graph.cellEditor.stopEditing;this.editor.graph.cellEditor.stopEditing=function(d,h){g.apply(this,arguments);a.updatePasteActionStates()};this.updatePasteActionStates()};
EditorUi.prototype.lazyZoomDelay=20;EditorUi.prototype.wheelZoomDelay=400;EditorUi.prototype.buttonZoomDelay=600;
EditorUi.prototype.initCanvas=function(){var a=this.editor.graph;a.timerAutoScroll=!0;a.getPagePadding=function(){return new mxPoint(Math.max(0,Math.round((a.container.offsetWidth-34)/a.view.scale)),Math.max(0,Math.round((a.container.offsetHeight-34)/a.view.scale)))};a.view.getBackgroundPageBounds=function(){var J=this.graph.getPageLayout(),aa=this.graph.getPageSize();return new mxRectangle(this.scale*(this.translate.x+J.x*aa.width),this.scale*(this.translate.y+J.y*aa.height),this.scale*J.width*aa.width,
this.scale*J.height*aa.height)};a.getPreferredPageSize=function(J,aa,ja){J=this.getPageLayout();aa=this.getPageSize();return new mxRectangle(0,0,J.width*aa.width,J.height*aa.height)};var b=null,f=this;if(this.editor.isChromelessView()){this.chromelessResize=b=mxUtils.bind(this,function(J,aa,ja,na){if(null!=a.container&&!a.isViewer()){ja=null!=ja?ja:0;na=null!=na?na:0;var X=a.pageVisible?a.view.getBackgroundPageBounds():a.getGraphBounds(),ea=mxUtils.hasScrollbars(a.container),sa=a.view.translate,ua=
a.view.scale,Ja=mxRectangle.fromRectangle(X);Ja.x=Ja.x/ua-sa.x;Ja.y=Ja.y/ua-sa.y;Ja.width/=ua;Ja.height/=ua;sa=a.container.scrollTop;var Ia=a.container.scrollLeft,va=8<=document.documentMode?20:14;if(8==document.documentMode||9==document.documentMode)va+=3;var Ba=a.container.offsetWidth-va;va=a.container.offsetHeight-va;J=J?Math.max(.3,Math.min(aa||1,Ba/Ja.width)):ua;aa=(Ba-J*Ja.width)/2/J;var qa=0==this.lightboxVerticalDivider?0:(va-J*Ja.height)/this.lightboxVerticalDivider/J;ea&&(aa=Math.max(aa,
0),qa=Math.max(qa,0));if(ea||X.width<Ba||X.height<va)a.view.scaleAndTranslate(J,Math.floor(aa-Ja.x),Math.floor(qa-Ja.y)),a.container.scrollTop=sa*J/ua,a.container.scrollLeft=Ia*J/ua;else if(0!=ja||0!=na)X=a.view.translate,a.view.setTranslate(Math.floor(X.x+ja/ua),Math.floor(X.y+na/ua))}});this.chromelessWindowResize=mxUtils.bind(this,function(){this.chromelessResize(!1)});var e=mxUtils.bind(this,function(){this.chromelessWindowResize(!1)});mxEvent.addListener(window,"resize",e);this.destroyFunctions.push(function(){mxEvent.removeListener(window,
"resize",e)});this.editor.addListener("resetGraphView",mxUtils.bind(this,function(){this.chromelessResize(!0)}));this.actions.get("zoomIn").funct=mxUtils.bind(this,function(J){a.zoomIn();this.chromelessResize(!1)});this.actions.get("zoomOut").funct=mxUtils.bind(this,function(J){a.zoomOut();this.chromelessResize(!1)});if("0"!=urlParams.toolbar){var g=JSON.parse(decodeURIComponent(urlParams["toolbar-config"]||"{}"));this.chromelessToolbar=document.createElement("div");this.chromelessToolbar.style.position=
"fixed";this.chromelessToolbar.style.overflow="hidden";this.chromelessToolbar.style.boxSizing="border-box";this.chromelessToolbar.style.whiteSpace="nowrap";this.chromelessToolbar.style.padding="10px 10px 8px 10px";this.chromelessToolbar.style.left=a.isViewer()?"0":"50%";mxClient.IS_IE||mxClient.IS_IE11?(this.chromelessToolbar.style.backgroundColor="#ffffff",this.chromelessToolbar.style.border="3px solid black"):this.chromelessToolbar.style.backgroundColor="#000000";mxUtils.setPrefixedStyle(this.chromelessToolbar.style,
"borderRadius","16px");mxUtils.setPrefixedStyle(this.chromelessToolbar.style,"transition","opacity 600ms ease-in-out");var d=mxUtils.bind(this,function(){var J=mxUtils.getCurrentStyle(a.container);a.isViewer()?this.chromelessToolbar.style.top="0":this.chromelessToolbar.style.bottom=(null!=J?parseInt(J["margin-bottom"]||0):0)+(null!=this.tabContainer?20+parseInt(this.tabContainer.style.height):20)+"px"});this.editor.addListener("resetGraphView",d);d();var h=0;d=mxUtils.bind(this,function(J,aa,ja){h++;
var na=document.createElement("span");na.style.paddingLeft="8px";na.style.paddingRight="8px";na.style.cursor="pointer";mxEvent.addListener(na,"click",J);null!=ja&&na.setAttribute("title",ja);J=document.createElement("img");J.setAttribute("border","0");J.setAttribute("src",aa);J.style.width="36px";J.style.filter="invert(100%)";na.appendChild(J);this.chromelessToolbar.appendChild(na);return na});if(null!=g.backBtn){var n=Graph.sanitizeLink(g.backBtn.url);null!=n&&d(mxUtils.bind(this,function(J){window.location.href=
n;mxEvent.consume(J)}),Editor.backImage,mxResources.get("back",null,"Back"))}if(this.isPagesEnabled()){var u=d(mxUtils.bind(this,function(J){this.actions.get("previousPage").funct();mxEvent.consume(J)}),Editor.previousImage,mxResources.get("previousPage")),m=document.createElement("div");m.style.fontFamily=Editor.defaultHtmlFont;m.style.display="inline-block";m.style.verticalAlign="top";m.style.fontWeight="bold";m.style.marginTop="8px";m.style.fontSize="14px";m.style.color=mxClient.IS_IE||mxClient.IS_IE11?
"#000000":"#ffffff";this.chromelessToolbar.appendChild(m);var r=d(mxUtils.bind(this,function(J){this.actions.get("nextPage").funct();mxEvent.consume(J)}),Editor.nextImage,mxResources.get("nextPage")),x=mxUtils.bind(this,function(){null!=this.pages&&1<this.pages.length&&null!=this.currentPage&&(m.innerText="",mxUtils.write(m,mxUtils.indexOf(this.pages,this.currentPage)+1+" / "+this.pages.length))});u.style.paddingLeft="0px";u.style.paddingRight="4px";r.style.paddingLeft="4px";r.style.paddingRight=
"0px";var B=mxUtils.bind(this,function(){null!=this.pages&&1<this.pages.length&&null!=this.currentPage?(r.style.display="",u.style.display="",m.style.display="inline-block"):(r.style.display="none",u.style.display="none",m.style.display="none");x()});this.editor.addListener("resetGraphView",B);this.editor.addListener("pageSelected",x)}d(mxUtils.bind(this,function(J){this.actions.get("zoomOut").funct();mxEvent.consume(J)}),Editor.zoomOutImage,mxResources.get("zoomOut")+" (Alt+Mousewheel)");d(mxUtils.bind(this,
function(J){this.actions.get("zoomIn").funct();mxEvent.consume(J)}),Editor.zoomInImage,mxResources.get("zoomIn")+" (Alt+Mousewheel)");d(mxUtils.bind(this,function(J){a.isLightboxView()?(1==a.view.scale?this.lightboxFit():a.zoomTo(1),this.chromelessResize(!1)):this.chromelessResize(!0);mxEvent.consume(J)}),Editor.zoomFitImage,mxResources.get("fit"));var C=null,F=null,H=mxUtils.bind(this,function(J){null!=C&&(window.clearTimeout(C),C=null);null!=F&&(window.clearTimeout(F),F=null);C=window.setTimeout(mxUtils.bind(this,
function(){mxUtils.setOpacity(this.chromelessToolbar,0);C=null;F=window.setTimeout(mxUtils.bind(this,function(){this.chromelessToolbar.style.display="none";F=null}),600)}),J||200)}),E=mxUtils.bind(this,function(J){null!=C&&(window.clearTimeout(C),C=null);null!=F&&(window.clearTimeout(F),F=null);this.chromelessToolbar.style.display="";mxUtils.setOpacity(this.chromelessToolbar,J||30)});if("1"==urlParams.layers){this.layersDialog=null;var N=d(mxUtils.bind(this,function(J){if(null!=this.layersDialog)this.layersDialog.parentNode.removeChild(this.layersDialog),
this.layersDialog=null;else{this.layersDialog=a.createLayersDialog(null,!0);mxEvent.addListener(this.layersDialog,"mouseleave",mxUtils.bind(this,function(){this.layersDialog.parentNode.removeChild(this.layersDialog);this.layersDialog=null}));var aa=N.getBoundingClientRect();mxUtils.setPrefixedStyle(this.layersDialog.style,"borderRadius","5px");this.layersDialog.style.position="fixed";this.layersDialog.style.fontFamily=Editor.defaultHtmlFont;this.layersDialog.style.width="160px";this.layersDialog.style.padding=
"4px 2px 4px 2px";this.layersDialog.style.left=aa.left+"px";this.layersDialog.style.bottom=parseInt(this.chromelessToolbar.style.bottom)+this.chromelessToolbar.offsetHeight+4+"px";mxClient.IS_IE||mxClient.IS_IE11?(this.layersDialog.style.backgroundColor="#ffffff",this.layersDialog.style.border="2px solid black",this.layersDialog.style.color="#000000"):(this.layersDialog.style.backgroundColor="#000000",this.layersDialog.style.color="#ffffff",mxUtils.setOpacity(this.layersDialog,80));aa=mxUtils.getCurrentStyle(this.editor.graph.container);
this.layersDialog.style.zIndex=aa.zIndex;document.body.appendChild(this.layersDialog);this.editor.fireEvent(new mxEventObject("layersDialogShown"))}mxEvent.consume(J)}),Editor.layersImage,mxResources.get("layers")),Q=a.getModel();Q.addListener(mxEvent.CHANGE,function(){N.style.display=1<Q.getChildCount(Q.root)?"":"none"})}("1"!=urlParams.openInSameWin||navigator.standalone)&&this.addChromelessToolbarItems(d);null==this.editor.editButtonLink&&null==this.editor.editButtonFunc||d(mxUtils.bind(this,function(J){null!=
this.editor.editButtonFunc?this.editor.editButtonFunc():"_blank"==this.editor.editButtonLink?this.editor.editAsNew(this.getEditBlankXml()):a.openLink(this.editor.editButtonLink,"editWindow");mxEvent.consume(J)}),Editor.editImage,mxResources.get("edit"));if(null!=this.lightboxToolbarActions)for(B=0;B<this.lightboxToolbarActions.length;B++){var S=this.lightboxToolbarActions[B];S.elem=d(S.fn,S.icon,S.tooltip)}if(null!=g.refreshBtn){var R=null==g.refreshBtn.url?null:Graph.sanitizeLink(g.refreshBtn.url);
d(mxUtils.bind(this,function(J){null!=R?window.location.href=R:window.location.reload();mxEvent.consume(J)}),Editor.refreshImage,mxResources.get("refresh",null,"Refresh"))}null!=g.fullscreenBtn&&window.self!==window.top&&d(mxUtils.bind(this,function(J){g.fullscreenBtn.url?a.openLink(g.fullscreenBtn.url):a.openLink(window.location.href);mxEvent.consume(J)}),Editor.fullscreenImage,mxResources.get("openInNewWindow",null,"Open in New Window"));(g.closeBtn&&window.self===window.top||a.lightbox&&("1"==
urlParams.close||this.container!=document.body))&&d(mxUtils.bind(this,function(J){"1"==urlParams.close||g.closeBtn?window.close():(this.destroy(),mxEvent.consume(J))}),Editor.closeImage,mxResources.get("close")+" (Escape)");this.chromelessToolbar.style.display="none";a.isViewer()||mxUtils.setPrefixedStyle(this.chromelessToolbar.style,"transform","translate(-50%,0)");a.container.appendChild(this.chromelessToolbar);mxEvent.addListener(a.container,mxClient.IS_POINTER?"pointermove":"mousemove",mxUtils.bind(this,
function(J){mxEvent.isTouchEvent(J)||(mxEvent.isShiftDown(J)||E(30),H())}));mxEvent.addListener(this.chromelessToolbar,mxClient.IS_POINTER?"pointermove":"mousemove",function(J){mxEvent.consume(J)});mxEvent.addListener(this.chromelessToolbar,"mouseenter",mxUtils.bind(this,function(J){a.tooltipHandler.resetTimer();a.tooltipHandler.hideTooltip();mxEvent.isShiftDown(J)?H():E(100)}));mxEvent.addListener(this.chromelessToolbar,"mousemove",mxUtils.bind(this,function(J){mxEvent.isShiftDown(J)?H():E(100);
mxEvent.consume(J)}));mxEvent.addListener(this.chromelessToolbar,"mouseleave",mxUtils.bind(this,function(J){mxEvent.isTouchEvent(J)||E(30)}));var ba=a.getTolerance();a.addMouseListener({startX:0,startY:0,scrollLeft:0,scrollTop:0,mouseDown:function(J,aa){this.startX=aa.getGraphX();this.startY=aa.getGraphY();this.scrollLeft=a.container.scrollLeft;this.scrollTop=a.container.scrollTop},mouseMove:function(J,aa){},mouseUp:function(J,aa){mxEvent.isTouchEvent(aa.getEvent())&&Math.abs(this.scrollLeft-a.container.scrollLeft)<
ba&&Math.abs(this.scrollTop-a.container.scrollTop)<ba&&Math.abs(this.startX-aa.getGraphX())<ba&&Math.abs(this.startY-aa.getGraphY())<ba&&(0<parseFloat(f.chromelessToolbar.style.opacity||0)?H():E(30))}})}this.editor.editable||this.addChromelessClickHandler()}else if(this.editor.extendCanvas){var T=a.view.validate;a.view.validate=function(){if(null!=this.graph.container&&mxUtils.hasScrollbars(this.graph.container)){var J=this.graph.getPagePadding(),aa=this.graph.getPageSize();this.translate.x=J.x-(this.x0||
0)*aa.width;this.translate.y=J.y-(this.y0||0)*aa.height}T.apply(this,arguments)};if(!a.isViewer()){var P=a.sizeDidChange;a.sizeDidChange=function(){if(null!=this.container&&mxUtils.hasScrollbars(this.container)){var J=this.getPageLayout(),aa=this.getPagePadding(),ja=this.getPageSize(),na=Math.ceil(2*aa.x+J.width*ja.width),X=Math.ceil(2*aa.y+J.height*ja.height),ea=a.minimumGraphSize;if(null==ea||ea.width!=na||ea.height!=X)a.minimumGraphSize=new mxRectangle(0,0,na,X);na=aa.x-J.x*ja.width;aa=aa.y-J.y*
ja.height;this.autoTranslate||this.view.translate.x==na&&this.view.translate.y==aa?P.apply(this,arguments):(this.autoTranslate=!0,this.view.x0=J.x,this.view.y0=J.y,J=a.view.translate.x,ja=a.view.translate.y,a.view.setTranslate(na,aa),a.container.scrollLeft+=Math.round((na-J)*a.view.scale),a.container.scrollTop+=Math.round((aa-ja)*a.view.scale),this.autoTranslate=!1)}else this.fireEvent(new mxEventObject(mxEvent.SIZE,"bounds",this.getGraphBounds()))}}}var Y=a.view.getBackgroundPane(),ka=a.view.getDrawPane();
a.cumulativeZoomFactor=1;var fa=null,ra=null,L=null,V=null,O=null,U=function(J){null!=fa&&window.clearTimeout(fa);0<=J&&window.setTimeout(function(){if(!a.isMouseDown||V)fa=window.setTimeout(mxUtils.bind(this,function(){a.isFastZoomEnabled()&&(null!=a.view.backgroundPageShape&&null!=a.view.backgroundPageShape.node&&(mxUtils.setPrefixedStyle(a.view.backgroundPageShape.node.style,"transform-origin",null),mxUtils.setPrefixedStyle(a.view.backgroundPageShape.node.style,"transform",null)),ka.style.transformOrigin=
"",Y.style.transformOrigin="",mxClient.IS_SF?(ka.style.transform="scale(1)",Y.style.transform="scale(1)",window.setTimeout(function(){ka.style.transform="";Y.style.transform=""},0)):(ka.style.transform="",Y.style.transform=""),a.view.getDecoratorPane().style.opacity="",a.view.getOverlayPane().style.opacity="");var aa=new mxPoint(a.container.scrollLeft,a.container.scrollTop),ja=mxUtils.getOffset(a.container),na=a.view.scale,X=0,ea=0;null!=ra&&(X=a.container.offsetWidth/2-ra.x+ja.x,ea=a.container.offsetHeight/
2-ra.y+ja.y);a.zoom(a.cumulativeZoomFactor,null,a.isFastZoomEnabled()?20:null);a.view.scale!=na&&(null!=L&&(X+=aa.x-L.x,ea+=aa.y-L.y),null!=b&&f.chromelessResize(!1,null,X*(a.cumulativeZoomFactor-1),ea*(a.cumulativeZoomFactor-1)),!mxUtils.hasScrollbars(a.container)||0==X&&0==ea||(a.container.scrollLeft-=X*(a.cumulativeZoomFactor-1),a.container.scrollTop-=ea*(a.cumulativeZoomFactor-1)));null!=O&&ka.setAttribute("filter",O);a.cumulativeZoomFactor=1;O=V=ra=L=fa=null}),null!=J?J:a.isFastZoomEnabled()?
f.wheelZoomDelay:f.lazyZoomDelay)},0)};a.lazyZoom=function(J,aa,ja,na){na=null!=na?na:this.zoomFactor;(aa=aa||!a.scrollbars)&&(ra=new mxPoint(a.container.offsetLeft+a.container.clientWidth/2,a.container.offsetTop+a.container.clientHeight/2));J?.15>=this.view.scale*this.cumulativeZoomFactor?this.cumulativeZoomFactor*=(this.view.scale+.05)/this.view.scale:(this.cumulativeZoomFactor*=na,this.cumulativeZoomFactor=Math.round(this.view.scale*this.cumulativeZoomFactor*100)/100/this.view.scale):.15>=this.view.scale*
this.cumulativeZoomFactor?this.cumulativeZoomFactor*=(this.view.scale-.05)/this.view.scale:(this.cumulativeZoomFactor/=na,this.cumulativeZoomFactor=Math.round(this.view.scale*this.cumulativeZoomFactor*100)/100/this.view.scale);this.cumulativeZoomFactor=Math.max(.05,Math.min(this.view.scale*this.cumulativeZoomFactor,160))/this.view.scale;a.isFastZoomEnabled()&&(null==O&&""!=ka.getAttribute("filter")&&(O=ka.getAttribute("filter"),ka.removeAttribute("filter")),L=new mxPoint(a.container.scrollLeft,a.container.scrollTop),
J=aa||null==ra?a.container.scrollLeft+a.container.clientWidth/2:ra.x+a.container.scrollLeft-a.container.offsetLeft,na=aa||null==ra?a.container.scrollTop+a.container.clientHeight/2:ra.y+a.container.scrollTop-a.container.offsetTop,ka.style.transformOrigin=J+"px "+na+"px",ka.style.transform="scale("+this.cumulativeZoomFactor+")",Y.style.transformOrigin=J+"px "+na+"px",Y.style.transform="scale("+this.cumulativeZoomFactor+")",null!=a.view.backgroundPageShape&&null!=a.view.backgroundPageShape.node&&(J=
a.view.backgroundPageShape.node,mxUtils.setPrefixedStyle(J.style,"transform-origin",(aa||null==ra?a.container.clientWidth/2+a.container.scrollLeft-J.offsetLeft+"px":ra.x+a.container.scrollLeft-J.offsetLeft-a.container.offsetLeft+"px")+" "+(aa||null==ra?a.container.clientHeight/2+a.container.scrollTop-J.offsetTop+"px":ra.y+a.container.scrollTop-J.offsetTop-a.container.offsetTop+"px")),mxUtils.setPrefixedStyle(J.style,"transform","scale("+this.cumulativeZoomFactor+")")),a.view.getDecoratorPane().style.opacity=
"0",a.view.getOverlayPane().style.opacity="0",null!=f.hoverIcons&&f.hoverIcons.reset());U(a.isFastZoomEnabled()?ja:0)};mxEvent.addGestureListeners(a.container,function(J){null!=fa&&window.clearTimeout(fa)},null,function(J){1!=a.cumulativeZoomFactor&&U(0)});mxEvent.addListener(a.container,"scroll",function(J){null==fa||a.isMouseDown||1==a.cumulativeZoomFactor||U(0)});mxEvent.addMouseWheelListener(mxUtils.bind(this,function(J,aa,ja,na,X){a.fireEvent(new mxEventObject("wheel"));if(null==this.dialogs||
0==this.dialogs.length)if(!a.scrollbars&&!ja&&a.isScrollWheelEvent(J))ja=a.view.getTranslate(),na=40/a.view.scale,mxEvent.isShiftDown(J)?a.view.setTranslate(ja.x+(aa?-na:na),ja.y):a.view.setTranslate(ja.x,ja.y+(aa?na:-na));else if(ja||a.isZoomWheelEvent(J))for(var ea=mxEvent.getSource(J);null!=ea;){if(ea==a.container)return a.tooltipHandler.hideTooltip(),ra=null!=na&&null!=X?new mxPoint(na,X):new mxPoint(mxEvent.getClientX(J),mxEvent.getClientY(J)),V=ja,ja=a.zoomFactor,na=null,J.ctrlKey&&null!=J.deltaY&&
40>Math.abs(J.deltaY)&&Math.round(J.deltaY)!=J.deltaY?ja=1+Math.abs(J.deltaY)/20*(ja-1):null!=J.movementY&&"pointermove"==J.type&&(ja=1+Math.max(1,Math.abs(J.movementY))/20*(ja-1),na=-1),a.lazyZoom(aa,null,na,ja),mxEvent.consume(J),!1;ea=ea.parentNode}}),a.container);a.panningHandler.zoomGraph=function(J){a.cumulativeZoomFactor=J.scale;a.lazyZoom(0<J.scale,!0);mxEvent.consume(J)}};
EditorUi.prototype.addChromelessToolbarItems=function(a){a(mxUtils.bind(this,function(b){this.actions.get("print").funct();mxEvent.consume(b)}),Editor.printImage,mxResources.get("print"))};EditorUi.prototype.isPagesEnabled=function(){return this.editor.editable||"1"!=urlParams["hide-pages"]};EditorUi.prototype.createTemporaryGraph=function(a){return Graph.createOffscreenGraph(a)};EditorUi.prototype.addChromelessClickHandler=function(){var a=urlParams.highlight;null!=a&&0<a.length&&(a="#"+a);this.editor.graph.addClickHandler(a)};
EditorUi.prototype.toggleFormatPanel=function(a){a=null!=a?a:0==this.formatWidth;null!=this.format&&(this.formatWidth=a?240:0,this.formatContainer.style.display=a?"":"none",this.refresh(),this.format.refresh(),this.fireEvent(new mxEventObject("formatWidthChanged")))};EditorUi.prototype.isFormatPanelVisible=function(){return 0<this.formatWidth};
EditorUi.prototype.lightboxFit=function(a){if(this.isDiagramEmpty())this.editor.graph.view.setScale(1);else{var b=urlParams.border,f=60;null!=b&&(f=parseInt(b));this.editor.graph.maxFitScale=this.lightboxMaxFitScale;this.editor.graph.fit(f,null,null,null,null,null,a);this.editor.graph.maxFitScale=null}};EditorUi.prototype.isDiagramEmpty=function(){var a=this.editor.graph.getModel();return 1==a.getChildCount(a.root)&&0==a.getChildCount(a.getChildAt(a.root,0))};
EditorUi.prototype.isSelectionAllowed=function(a){return"SELECT"==mxEvent.getSource(a).nodeName||"INPUT"==mxEvent.getSource(a).nodeName&&mxUtils.isAncestorNode(this.formatContainer,mxEvent.getSource(a))};EditorUi.prototype.addBeforeUnloadListener=function(){window.onbeforeunload=mxUtils.bind(this,function(){if(!this.editor.isChromelessView())return this.onBeforeUnload()})};EditorUi.prototype.onBeforeUnload=function(){if(this.editor.modified)return mxResources.get("allChangesLost")};
EditorUi.prototype.open=function(){try{null!=window.opener&&null!=window.opener.openFile&&window.opener.openFile.setConsumer(mxUtils.bind(this,function(a,b){try{var f=mxUtils.parseXml(a);this.editor.setGraphXml(f.documentElement);this.editor.setModified(!1);this.editor.undoManager.clear();null!=b&&(this.editor.setFilename(b),this.updateDocumentTitle())}catch(e){mxUtils.alert(mxResources.get("invalidOrMissingFile")+": "+e.message)}}))}catch(a){}this.editor.graph.view.validate();this.editor.graph.sizeDidChange();
this.editor.fireEvent(new mxEventObject("resetGraphView"))};EditorUi.prototype.showPopupMenu=function(a,b,f,e){this.editor.graph.popupMenuHandler.hideMenu();var g=new mxPopupMenu(a);g.div.className+=" geMenubarMenu";g.smartSeparators=!0;g.showDisabled=!0;g.autoExpand=!0;g.hideMenu=mxUtils.bind(this,function(){mxPopupMenu.prototype.hideMenu.apply(g,arguments);g.destroy()});g.popup(b,f,null,e);this.setCurrentMenu(g)};
EditorUi.prototype.setCurrentMenu=function(a,b){this.currentMenuElt=b;this.currentMenu=a;this.hideShapePicker()};EditorUi.prototype.resetCurrentMenu=function(){this.currentMenu=this.currentMenuElt=null};EditorUi.prototype.hideCurrentMenu=function(){null!=this.currentMenu&&(this.currentMenu.hideMenu(),this.resetCurrentMenu())};EditorUi.prototype.updateDocumentTitle=function(){var a=this.editor.getOrCreateFilename();null!=this.editor.appName&&(a+=" - "+this.editor.appName);document.title=a};
EditorUi.prototype.createHoverIcons=function(){return new HoverIcons(this.editor.graph)};EditorUi.prototype.redo=function(){try{this.editor.graph.isEditing()?document.execCommand("redo",!1,null):this.editor.undoManager.redo()}catch(a){}};EditorUi.prototype.undo=function(){try{var a=this.editor.graph;if(a.isEditing()){var b=a.cellEditor.textarea.innerHTML;document.execCommand("undo",!1,null);b==a.cellEditor.textarea.innerHTML&&(a.stopEditing(!0),this.editor.undoManager.undo())}else this.editor.undoManager.undo()}catch(f){}};
EditorUi.prototype.canRedo=function(){return this.editor.graph.isEditing()||this.editor.undoManager.canRedo()};EditorUi.prototype.canUndo=function(){return this.editor.graph.isEditing()||this.editor.undoManager.canUndo()};EditorUi.prototype.getEditBlankXml=function(){return mxUtils.getXml(this.editor.getGraphXml())};EditorUi.prototype.getUrl=function(a){a=null!=a?a:window.location.pathname;var b=0<a.indexOf("?")?1:0,f;for(f in urlParams)a=0==b?a+"?":a+"&",a+=f+"="+urlParams[f],b++;return a};
EditorUi.prototype.setScrollbars=function(a){var b=this.editor.graph,f=b.container.style.overflow;b.scrollbars=a;this.editor.updateGraphComponents();f!=b.container.style.overflow&&(b.container.scrollTop=0,b.container.scrollLeft=0,b.view.scaleAndTranslate(1,0,0),this.resetScrollbars());this.fireEvent(new mxEventObject("scrollbarsChanged"))};EditorUi.prototype.hasScrollbars=function(){return this.editor.graph.scrollbars};
EditorUi.prototype.resetScrollbars=function(){var a=this.editor.graph;if(!this.editor.extendCanvas)a.container.scrollTop=0,a.container.scrollLeft=0,mxUtils.hasScrollbars(a.container)||a.view.setTranslate(0,0);else if(!this.editor.isChromelessView())if(mxUtils.hasScrollbars(a.container))if(a.pageVisible){var b=a.getPagePadding();a.container.scrollTop=Math.floor(b.y-this.editor.initialTopSpacing)-1;a.container.scrollLeft=Math.floor(Math.min(b.x,(a.container.scrollWidth-a.container.clientWidth)/2))-
1;b=a.getGraphBounds();0<b.width&&0<b.height&&(b.x>a.container.scrollLeft+.9*a.container.clientWidth&&(a.container.scrollLeft=Math.min(b.x+b.width-a.container.clientWidth,b.x-10)),b.y>a.container.scrollTop+.9*a.container.clientHeight&&(a.container.scrollTop=Math.min(b.y+b.height-a.container.clientHeight,b.y-10)))}else{b=a.getGraphBounds();var f=Math.max(b.width,a.scrollTileSize.width*a.view.scale);a.container.scrollTop=Math.floor(Math.max(0,b.y-Math.max(20,(a.container.clientHeight-Math.max(b.height,
a.scrollTileSize.height*a.view.scale))/4)));a.container.scrollLeft=Math.floor(Math.max(0,b.x-Math.max(0,(a.container.clientWidth-f)/2)))}else{b=mxRectangle.fromRectangle(a.pageVisible?a.view.getBackgroundPageBounds():a.getGraphBounds());f=a.view.translate;var e=a.view.scale;b.x=b.x/e-f.x;b.y=b.y/e-f.y;b.width/=e;b.height/=e;a.view.setTranslate(Math.floor(Math.max(0,(a.container.clientWidth-b.width)/2)-b.x+2),Math.floor((a.pageVisible?0:Math.max(0,(a.container.clientHeight-b.height)/4))-b.y+1))}};